(()=>{'use strict';
let token='',me=null,S={projects:[],shifts:[],attendance:null,assignments:[],notifications:[]};
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const API=()=>String(window.APP_CONFIG?.API_URL||'').trim();
const today=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const monthNow=()=>today().slice(0,7);
function updateConfigMessage(){const el=$('configMsg');if(!el)return;if(API()){el.classList.add('hidden');el.textContent=''}else{el.classList.remove('hidden');el.textContent='Không đọc được API_URL từ config.js. Hãy tải lại đúng bộ GitHub đồng bộ.'}}
function ensureApi(){if(!API())throw Error('API_URL chưa được nạp từ config.js. Hãy kiểm tra index.html → config.js → app.js.')}
async function api(action,payload={}){ensureApi();const r=await fetch(API(),{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},cache:'no-store',body:JSON.stringify({action,payload,token})});const x=await r.json().catch(()=>({ok:false,error:'Phản hồi máy chủ không hợp lệ.'}));if(!x.ok)throw Error(x.error||'API_ERROR');return x}
function setMsg(id,text,error=false){const e=$(id);if(!e)return;e.textContent=text||'';e.className=error?'err':'ok'}
function net(){const n=$('net');if(!n)return;n.textContent=navigator.onLine?'ONLINE':'OFFLINE';n.className='status '+(navigator.onLine?'':'off')}
function deviceId(){let x=localStorage.getItem('ct_device_id');if(!x){x=crypto.randomUUID();localStorage.setItem('ct_device_id',x)}return x}
function queue(){try{return JSON.parse(localStorage.getItem('ct_offline_queue')||'[]')}catch{return[]}}
function saveQueue(q){localStorage.setItem('ct_offline_queue',JSON.stringify(q.slice(-100)))}
async function login(){const b=$('loginBtn');b.disabled=true;setMsg('msg','');try{const x=await api('login',{phone:$('phone').value,password:$('password').value});token=x.token;me=x.me;await boot();if(x.forcePasswordChange)passwordModal()}catch(e){setMsg('msg',e.message,true)}finally{b.disabled=false}}
async function boot(){const x=await api('bootstrap');S={projects:x.projects||[],shifts:x.shifts||[],attendance:x.attendance||null,assignments:x.assignments||[],notifications:x.notifications||[]};me=x.me;$('login').classList.add('hidden');$('app').classList.remove('hidden');$('name').textContent=me.NAME||'-';$('role').textContent=me.ROLE==='ADMIN'?'QUẢN TRỊ VIÊN':'NHÂN VIÊN';$('adminTab').classList.toggle('hidden',me.ROLE!=='ADMIN');$('force').classList.toggle('hidden',me.FORCE_PASSWORD_CHANGE!=='YES');$('project').innerHTML=S.projects.map(p=>`<option value="${esc(p.PROJECT_ID)}">${esc(p.PROJECT_NAME)}</option>`).join('')||'<option value="">Chưa có công trình</option>';if(me.ROLE==='ADMIN'){document.querySelector('#tabs').insertBefore($('adminTab'),document.querySelector('#tabs').firstElementChild)}renderAttendance();renderJobs();renderNotifications();await renderHistory();await renderStats();if(me.ROLE==='ADMIN'){tab('admin');await admin('dashboard')}else tab('attendance');flushQueue()}
function renderAttendance(){const a=S.attendance,open=a&&String(a.STATE)==='OPEN',closed=a&&String(a.STATE)==='CLOSED';$('in').disabled=!!open||!!closed;$('out').disabled=!open;$('state').textContent=closed?'ĐÃ HOÀN TẤT':open?'ĐÃ VÀO – CHỜ RA':'CHƯA VÀO';if(a&&a.PROJECT_ID)$('project').value=a.PROJECT_ID}
function renderJobs(){$('jobsList').innerHTML=S.assignments.length?S.assignments.map(x=>`<div class="row"><div><b>${esc(x.TASK_TITLE||'Công việc')}</b><small>${esc(x.START_TIME||'')} – ${esc(x.END_TIME||'')}</small><small>${esc(x.NOTE||'')}</small></div><span class="badge">${esc(x.STATUS||'ACTIVE')}</span></div>`).join(''):'<div class="empty">Chưa có công việc được phân công.</div>'}
function renderNotifications(){const b=$('bell');if(!b)return;b.textContent=S.notifications.length?'🔔 '+S.notifications.length:'🔔';b.onclick=()=>{if(!S.notifications.length){alert('Không có thông báo mới.');return}modal(`<h2>THÔNG BÁO</h2>${S.notifications.map(n=>`<div class="row"><div><b>${esc(n.TITLE)}</b><small>${esc(n.MESSAGE)}</small></div><button class="mini" data-notification="${esc(n.NOTIFICATION_ID)}">Đã xem</button></div>`).join('')}<div class="actions"><button class="secondary" data-close-modal>ĐÓNG</button></div>`)} }
async function renderHistory(){try{const x=await api('monthlyStats',{month:monthNow()});$('historyList').innerHTML=(x.records||[]).slice().reverse().slice(0,50).map(r=>`<div class="row"><div><b>${esc(r.WORK_DATE)}</b><small>${esc(r.CHECKIN_TIME||'-')} → ${esc(r.CHECKOUT_TIME||'-')}</small></div><span class="badge">${esc(r.STATUS||'-')}</span></div>`).join('')||'<div class="empty">Chưa có dữ liệu.</div>'}catch(e){$('historyList').innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}
async function renderStats(){const m=$('statsMonth')?.value||monthNow();try{const x=await api('monthlyStats',{month:m});$('statsGrid').innerHTML=[['Ngày công',x.totalDays],['Giờ công',Number(x.totalHours||0).toFixed(2)],['Đi muộn',x.late],['Về sớm',x.early],['Bản ghi',(x.records||[]).length]].map(a=>`<div class="stat"><small>${a[0]}</small><b>${a[1]}</b></div>`).join('')}catch(e){$('statsGrid').innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}
function gps(){return new Promise((ok,no)=>navigator.geolocation.getCurrentPosition(p=>ok(p.coords),e=>no(Error('Không lấy được GPS: '+e.message)),{enableHighAccuracy:true,timeout:15000,maximumAge:0}))}
async function attendance(action){$('attMsg').textContent='Đang lấy GPS...';try{const c=await gps();$('gps').textContent=`GPS: ${c.latitude.toFixed(6)}, ${c.longitude.toFixed(6)} ± ${Math.round(c.accuracy||0)}m`;const ev={eventId:crypto.randomUUID(),action,PROJECT_ID:$('project').value,eventTime:new Date().toISOString(),lat:c.latitude,lng:c.longitude,accuracy:c.accuracy,deviceId:deviceId()};if(!navigator.onLine){if(!token)throw Error('Cần đăng nhập online trước khi chấm công offline.');const q=queue();q.push(ev);saveQueue(q);$('attMsg').textContent='Đã lưu OFFLINE. Sẽ tự đồng bộ khi có mạng.';if(action==='CHECKIN'){$('in').disabled=true;$('out').disabled=false;$('state').textContent='ĐÃ VÀO – CHỜ RA (OFFLINE)'}else{$('out').disabled=true;$('state').textContent='ĐÃ GHI RA (OFFLINE)'}return}const q=await api(action==='CHECKIN'?'checkinPreview':'checkoutPreview',ev);if(q.warning?.length&&!confirm('Cảnh báo:\n• '+q.warning.join('\n• ')+'\n\nBạn có muốn TIẾP TỤC không?'))return;await api('commitPreview',{previewToken:q.previewToken});await boot();$('attMsg').textContent='Đã ghi nhận.'}catch(e){$('attMsg').textContent=e.message}}
async function flushQueue(){if(!navigator.onLine||!token)return;const q=queue();if(!q.length)return;try{const r=await api('syncEvents',{events:q});const failed=(r.results||[]).filter(x=>!x.ok);const failedIds=new Set(failed.map(x=>String(x.eventId)));saveQueue(q.filter(e=>failedIds.has(String(e.eventId))));if(!failed.length){setMsg('attMsg','Dữ liệu OFFLINE đã đồng bộ.');await boot()}}catch{}}
function passwordModal(){modal(`<h2>ĐỔI MẬT KHẨU</h2><p class="muted">Mật khẩu mới tối thiểu 8 ký tự.</p><label>Mật khẩu mới<input id="np" type="password"></label><label>Xác nhận<input id="np2" type="password"></label><div id="pm"></div><div class="actions"><button class="secondary" data-close-modal>HỦY</button><button class="primary" id="ps">LƯU</button></div>`);$('ps').onclick=async()=>{if($('np').value.length<8||$('np').value!==$('np2').value){setMsg('pm','Mật khẩu không hợp lệ.',true);return}try{await api('changePassword',{newPassword:$('np').value});closeModal();me.FORCE_PASSWORD_CHANGE='NO';$('force').classList.add('hidden')}catch(e){setMsg('pm',e.message,true)}}}
function modal(html){$('modal').innerHTML='<div>'+html+'</div>';$('modal').classList.remove('hidden')}
function closeModal(){$('modal').classList.add('hidden');$('modal').innerHTML=''}
async function leave(){try{if(!$('leaveDate').value)throw Error('Chọn ngày nghỉ.');await api('leaveRequest',{WORK_DATE:$('leaveDate').value,TYPE:$('leaveType').value,SHIFT:$('leaveShift').value,REASON:$('leaveReason').value});setMsg('leaveMsg','Đã gửi đề nghị.')}catch(e){setMsg('leaveMsg',e.message,true)}}
async function logout(){try{await api('logout')}catch{}token='';me=null;location.reload()}
function tab(n){document.querySelectorAll('#tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===n));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('hidden',p.id!==n))}
function table(rows,cols,actions=''){if(!rows?.length)return '<div class="empty">Không có dữ liệu.</div>';return '<div class="table"><table><thead><tr>'+cols.map(c=>`<th>${c}</th>`).join('')+(actions?'<th>THAO TÁC</th>':'')+'</tr></thead><tbody>'+rows.map((r,i)=>'<tr>'+cols.map(c=>`<td>${esc(r[c])}</td>`).join('')+(actions?`<td>${actions.replaceAll('{i}',i).replaceAll('{id}',esc(r[actionsKey(actions)]||''))}</td>`:'')+'</tr>').join('')+'</tbody></table></div>'}
function actionsKey(){return 'EMPLOYEE_ID'}
function formButtons(label='LƯU'){return `<div class="form-actions"><button class="secondary" data-close-admin>HỦY</button><button class="primary" type="submit">${label}</button></div>`}
function adminList(rows,kind){
 if(!rows?.length)return '<div class="empty">Không có dữ liệu.</div>';
 return rows.map((r,i)=>{
   let title='',sub='';
   if(kind==='employees'){title=`${esc(r.NAME)} · ${esc(r.EMPLOYEE_ID)}`;sub=`${esc(r.PHONE)} · ${esc(r.ROLE)} · ${esc(r.STATUS)}`}
   if(kind==='projects'){title=`${esc(r.PROJECT_NAME)} · ${esc(r.PROJECT_ID)}`;sub=`${esc(r.ADDRESS||'')} · ${esc(r.LAT)}, ${esc(r.LNG)} · bán kính ${esc(r.RADIUS_M)}m · ${esc(r.STATUS)}`}
   if(kind==='shifts'){title=`${esc(r.SHIFT_NAME)} · ${esc(r.SHIFT_ID)}`;sub=`${esc(r.START_TIME)} – ${esc(r.END_TIME)} · sớm ${esc(r.EARLY_TOL_MIN)}p · trễ ${esc(r.LATE_TOL_MIN)}p · ${esc(r.STATUS)}`}
   if(kind==='groups'){title=`${esc(r.GROUP_NAME)} · ${esc(r.GROUP_ID)}`;sub=`Trưởng nhóm: ${esc(r.LEADER_ID||'-')} · ${esc(r.STATUS)}`}
   return `<div class="row"><div><b>${title}</b><small>${sub}</small></div><div class="row-actions"><button class="mini" data-edit-${kind}="${esc(i)}">Sửa</button></div></div>`
 }).join('')
}
function csvDownload(rows,name){if(!rows?.length){alert('Không có dữ liệu để xuất.');return}const keys=[...new Set(rows.flatMap(r=>Object.keys(r)))];const q=v=>`"${String(v??'').replaceAll('"','""')}"`;const csv='\uFEFF'+keys.map(q).join(',')+'\n'+rows.map(r=>keys.map(k=>q(r[k])).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function admin(kind){document.querySelectorAll('.admin-menu button').forEach(b=>b.classList.toggle('active',b.dataset.admin===kind));const box=$('adminContent');box.innerHTML='<div class="empty">Đang tải...</div>';try{
 if(kind==='dashboard'){const x=await api('adminDashboard');box.innerHTML=`<div class="admin-title"><h2>TỔNG QUAN</h2></div><div class="stats">${[['Nhân viên',x.activeUsers],['Chờ duyệt',x.pendingAttendance],['Công trình',x.projects],['Nhóm',x.groups]].map(a=>`<div class="stat"><small>${a[0]}</small><b>${a[1]}</b></div>`).join('')}</div>`;return}
 if(kind==='employees'){const x=await api('adminEmployees');box.innerHTML=`<div class="admin-title"><h2>NHÂN VIÊN</h2><button class="secondary" data-new="employee">＋ Thêm</button></div>${adminList(x.rows,'employees')}`;box._rows=x.rows;return}
 if(kind==='projects'){const x=await api('adminProjects');box.innerHTML=`<div class="admin-title"><h2>CÔNG TRÌNH</h2><button class="secondary" data-new="project">＋ Thêm</button></div>${adminList(x.rows,'projects')}`;box._rows=x.rows;return}
 if(kind==='shifts'){const x=await api('adminShifts');box.innerHTML=`<div class="admin-title"><h2>CA LÀM</h2><button class="secondary" data-new="shift">＋ Thêm</button></div>${adminList(x.rows,'shifts')}`;box._rows=x.rows;return}
 if(kind==='attendance'){const x=await api('adminAttendance',{month:monthNow()});box.innerHTML=`<div class="admin-title"><h2>DUYỆT CÔNG</h2><span class="muted">Tháng ${esc(monthNow())}</span></div>`+((x.rows||[]).map(r=>`<div class="row"><div><b>${esc(r.EMPLOYEE_ID)} · ${esc(r.WORK_DATE)}</b><small>${esc(r.CHECKIN_TIME||'')} → ${esc(r.CHECKOUT_TIME||'')} | ${esc(r.STATUS||'')}</small><small>GPS: ${esc(r.GPS_WARNING||'OK')} · Giờ: ${esc(r.CHECKIN_TIME_WARNING||'')}${r.CHECKOUT_TIME_WARNING?' / '+esc(r.CHECKOUT_TIME_WARNING):''}</small></div><div class="row-actions"><button class="mini" data-approve="${esc(r.ATTENDANCE_ID)}" data-status="APPROVED">Duyệt</button><button class="mini danger" data-approve="${esc(r.ATTENDANCE_ID)}" data-status="REJECTED">Từ chối</button></div></div>`).join('')||'<div class="empty">Không có dữ liệu.</div>');return}
 if(kind==='makeup'){const [e,p,s]=await Promise.all([api('adminEmployees'),api('adminProjects'),api('adminShifts')]);box.innerHTML=`<div class="admin-title"><h2>CHẤM CÔNG BỔ SUNG</h2></div><form id="makeupForm"><div class="formgrid"><label>Nhân viên<select name="EMPLOYEE_ID">${e.rows.filter(r=>r.STATUS==='ACTIVE').map(r=>`<option value="${esc(r.EMPLOYEE_ID)}">${esc(r.NAME)} · ${esc(r.EMPLOYEE_ID)}</option>`).join('')}</select></label><label>Ngày<input name="WORK_DATE" type="date" value="${today()}"></label><label>Công trình<select name="PROJECT_ID">${p.rows.map(r=>`<option value="${esc(r.PROJECT_ID)}">${esc(r.PROJECT_NAME)}</option>`).join('')}</select></label><label>Ca<select name="SHIFT_ID">${s.rows.map(r=>`<option value="${esc(r.SHIFT_ID)}">${esc(r.SHIFT_NAME)} ${esc(r.START_TIME)}-${esc(r.END_TIME)}</option>`).join('')}</select></label><label>Loại<select name="MAKEUP_TYPE"><option value="FULL">Đủ ca</option><option value="HALF">Nửa ca</option></select></label><label>Phần ca<select name="SHIFT_PART"><option value="SANG">Sáng</option><option value="CHIEU">Chiều</option><option value="TOI">Tối</option></select></label><label>Giờ VÀO<input name="CHECKIN_TIME" type="datetime-local"></label><label>Giờ RA<input name="CHECKOUT_TIME" type="datetime-local"></label><label class="full">Lý do<textarea name="REASON" rows="3"></textarea></label></div>${formButtons('TẠO PHIẾU')}</form><div id="makeupMsg"></div>`;box.querySelector('#makeupForm').onsubmit=async ev=>{ev.preventDefault();try{await api('adminMakeup',parseForm(ev.target));setMsg('makeupMsg','Đã tạo phiếu chấm công bổ sung.')}catch(e){setMsg('makeupMsg',e.message,true)}};return}
 if(kind==='groups'){const [g,e]=await Promise.all([api('adminGroups'),api('adminEmployees')]);box.innerHTML=`<div class="admin-title"><h2>NHÓM LÀM VIỆC</h2><button class="secondary" data-new="group">＋ Thêm</button></div>${adminList(g.rows,'groups')}`;box._rows=g.rows;return}
 if(kind==='assignments'){const [a,g,p,s,e]=await Promise.all([api('adminAssignments',{WORK_DATE:today()}),api('adminGroups'),api('adminProjects'),api('adminShifts'),api('adminEmployees')]);box.innerHTML=`<div class="admin-title"><h2>PHÂN CÔNG HÔM NAY</h2><button class="secondary" data-new="assignment">＋ Thêm</button></div>${(a.rows||[]).map(r=>`<div class="row"><div><b>${esc(r.TASK_TITLE||'')}</b><small>${esc(r.WORK_DATE)} · ${esc(r.GROUP_ID)} · ${esc(r.PROJECT_ID)} · ${esc(r.SHIFT_ID)}</small><small>${esc(r.START_TIME)}–${esc(r.END_TIME)} ${esc(r.NOTE||'')}</small></div><div class="row-actions"><button class="mini" data-edit-assignment="${esc(r.ASSIGNMENT_ID)}">Sửa</button><button class="mini danger" data-delete-assignment="${esc(r.ASSIGNMENT_ID)}">Xóa</button></div></div>`).join('')||'<div class="empty">Chưa có phân công hôm nay.</div>'}<div id="assignmentCache" class="hidden" data-groups='${esc(JSON.stringify(g.rows))}' data-projects='${esc(JSON.stringify(p.rows))}' data-shifts='${esc(JSON.stringify(s.rows))}' data-employees='${esc(JSON.stringify(e.rows))}'></div>`;return}
 if(kind==='leave'){const x=await api('adminLeave',{STATUS:'PENDING'});box.innerHTML='<div class="admin-title"><h2>NGHỈ PHÉP CHỜ DUYỆT</h2></div>'+((x.rows||[]).map(r=>`<div class="row"><div><b>${esc(r.EMPLOYEE_ID)} · ${esc(r.WORK_DATE)} · ${esc(r.TYPE)}</b><small>${esc(r.SHIFT||'')} · ${esc(r.REASON||'')}</small></div><div class="row-actions"><button class="mini" data-leave="${esc(r.LEAVE_ID)}" data-status="APPROVED">Duyệt</button><button class="mini danger" data-leave="${esc(r.LEAVE_ID)}" data-status="REJECTED">Từ chối</button></div></div>`).join('')||'<div class="empty">Không có đơn chờ duyệt.</div>');return}
 if(kind==='notifications'){const [n,e]=await Promise.all([api('adminNotifications'),api('adminEmployees')]);box.innerHTML=`<div class="admin-title"><h2>THÔNG BÁO</h2><button class="secondary" data-new="notification">＋ Gửi</button></div>`+table(n.rows,['NOTIFICATION_ID','EMPLOYEE_ID','TITLE','MESSAGE','CREATED_AT','READ_AT']);return}
 if(kind==='reports'){const x=await api('adminReports',{month:monthNow()});box.innerHTML=`<div class="admin-title"><h2>BÁO CÁO ${esc(x.month)}</h2><button class="secondary" data-report-copy>Xuất dữ liệu</button></div><div class="muted">Tiêu đề báo cáo lấy từ CAU_HINH_BAO_CAO; dữ liệu tổng hợp theo CHAM_CONG.</div>${table(x.rows,['EMPLOYEE_ID','NAME','DAYS','HOURS','RECORDS','PENDING'])}`;return}
 if(kind==='logs'){const x=await api('adminLogs');box.innerHTML='<div class="admin-title"><h2>NHẬT KÝ</h2></div>'+table(x.rows,['TIME','ACTION','USER_ID','DETAIL']);return}
 }catch(e){box.innerHTML=`<div class="err">${esc(e.message)}</div>`}}
function parseForm(f){const o={};new FormData(f).forEach((v,k)=>o[k]=String(v));return o}
function showEmployeeForm(row={}){modal(`<h2>${row.EMPLOYEE_ID?'SỬA':'THÊM'} NHÂN VIÊN</h2><form id="employeeForm"><div class="formgrid"><label>Mã nhân viên<input name="EMPLOYEE_ID" value="${esc(row.EMPLOYEE_ID||'') }" required ${row.EMPLOYEE_ID?'readonly':''}></label><label>Họ tên<input name="NAME" value="${esc(row.NAME||'')}" required></label><label>Số điện thoại<input name="PHONE" inputmode="tel" value="${esc(row.PHONE||'')}" required></label><label>Vai trò<select name="ROLE"><option ${row.ROLE==='USER'?'selected':''}>USER</option><option ${row.ROLE==='ADMIN'?'selected':''}>ADMIN</option></select></label><label>Trạng thái<select name="STATUS"><option ${row.STATUS!=='INACTIVE'?'selected':''}>ACTIVE</option><option ${row.STATUS==='INACTIVE'?'selected':''}>INACTIVE</option></select></label><label>${row.EMPLOYEE_ID?'Mật khẩu mới (bỏ trống nếu giữ nguyên)':'Mật khẩu ban đầu'}<input name="password" type="password" minlength="8" ${row.EMPLOYEE_ID?'':'required'}></label></div><p class="muted">Tài khoản mới hoặc khi đổi mật khẩu sẽ buộc đổi mật khẩu ở lần đăng nhập tiếp theo.</p>${formButtons()}</form><div id="formMsg"></div>`);$('employeeForm').onsubmit=async ev=>{ev.preventDefault();try{await api('adminSaveEmployee',parseForm(ev.target));closeModal();admin('employees')}catch(e){setMsg('formMsg',e.message,true)}}}
function showProjectForm(row={}){modal(`<h2>${row.PROJECT_ID?'SỬA':'THÊM'} CÔNG TRÌNH</h2><form id="projectForm"><div class="formgrid"><label>Mã công trình<input name="PROJECT_ID" value="${esc(row.PROJECT_ID||'')}" required></label><label>Tên công trình<input name="PROJECT_NAME" value="${esc(row.PROJECT_NAME||'')}" required></label><label class="full">Địa chỉ<input name="ADDRESS" value="${esc(row.ADDRESS||'')}"></label><label class="full">Tọa độ Google Maps<input name="COORDINATES" value="${row.LAT&&row.LNG?esc(row.LAT+', '+row.LNG):''}" placeholder="16.467812, 107.590421" required></label><label>Bán kính (m)<input name="RADIUS_M" type="number" min="10" value="${esc(row.RADIUS_M||100)}"></label><label>Trạng thái<select name="STATUS"><option ${row.STATUS!=='INACTIVE'?'selected':''}>ACTIVE</option><option ${row.STATUS==='INACTIVE'?'selected':''}>INACTIVE</option></select></label></div>${formButtons()}</form><div id="formMsg"></div>`);$('projectForm').onsubmit=async ev=>{ev.preventDefault();try{await api('adminSaveProject',parseForm(ev.target));closeModal();admin('projects')}catch(e){setMsg('formMsg',e.message,true)}}}
function showShiftForm(row={}){modal(`<h2>${row.SHIFT_ID?'SỬA':'THÊM'} CA LÀM</h2><form id="shiftForm"><div class="formgrid"><label>Mã ca<input name="SHIFT_ID" value="${esc(row.SHIFT_ID||'')}" required></label><label>Tên ca<input name="SHIFT_NAME" value="${esc(row.SHIFT_NAME||'')}" required></label><label>Giờ bắt đầu<input name="START_TIME" type="time" value="${esc(row.START_TIME||'')}" required></label><label>Giờ kết thúc<input name="END_TIME" type="time" value="${esc(row.END_TIME||'')}" required></label><label>Cho phép vào sớm (phút)<input name="EARLY_TOL_MIN" type="number" min="0" value="${esc(row.EARLY_TOL_MIN||0)}"></label><label>Cho phép trễ (phút)<input name="LATE_TOL_MIN" type="number" min="0" value="${esc(row.LATE_TOL_MIN||15)}"></label><label>Trạng thái<select name="STATUS"><option ${row.STATUS!=='INACTIVE'?'selected':''}>ACTIVE</option><option ${row.STATUS==='INACTIVE'?'selected':''}>INACTIVE</option></select></label></div>${formButtons()}</form><div id="formMsg"></div>`);$('shiftForm').onsubmit=async ev=>{ev.preventDefault();try{await api('adminSaveShift',parseForm(ev.target));closeModal();admin('shifts')}catch(e){setMsg('formMsg',e.message,true)}}}
function showGroupForm(row={}){modal(`<h2>${row.GROUP_ID?'SỬA':'THÊM'} NHÓM</h2><form id="groupForm"><div class="formgrid"><label>Mã nhóm<input name="GROUP_ID" value="${esc(row.GROUP_ID||'')}" required></label><label>Tên nhóm<input name="GROUP_NAME" value="${esc(row.GROUP_NAME||'')}" required></label><label>Trưởng nhóm<input name="LEADER_ID" value="${esc(row.LEADER_ID||'')}"></label><label>Trạng thái<select name="STATUS"><option>ACTIVE</option><option ${row.STATUS==='INACTIVE'?'selected':''}>INACTIVE</option></select></label></div>${formButtons()}</form><div id="formMsg"></div>`);$('groupForm').onsubmit=async ev=>{ev.preventDefault();try{await api('adminSaveGroup',parseForm(ev.target));closeModal();admin('groups')}catch(e){setMsg('formMsg',e.message,true)}}}
async function showAssignmentForm(row={}){const [g,p,s,e]=await Promise.all([api('adminGroups'),api('adminProjects'),api('adminShifts'),api('adminEmployees')]);modal(`<h2>${row.ASSIGNMENT_ID?'SỬA':'TẠO'} PHÂN CÔNG</h2><form id="assignmentForm"><input type="hidden" name="ASSIGNMENT_ID" value="${esc(row.ASSIGNMENT_ID||'')}"><div class="formgrid"><label>Ngày<input name="WORK_DATE" type="date" value="${esc(row.WORK_DATE||today())}" required></label><label>Nhóm<select name="GROUP_ID">${g.rows.map(x=>`<option value="${esc(x.GROUP_ID)}" ${x.GROUP_ID===row.GROUP_ID?'selected':''}>${esc(x.GROUP_NAME)}</option>`).join('')}</select></label><label>Công trình<select name="PROJECT_ID">${p.rows.map(x=>`<option value="${esc(x.PROJECT_ID)}" ${x.PROJECT_ID===row.PROJECT_ID?'selected':''}>${esc(x.PROJECT_NAME)}</option>`).join('')}</select></label><label>Ca<select name="SHIFT_ID">${s.rows.map(x=>`<option value="${esc(x.SHIFT_ID)}" ${x.SHIFT_ID===row.SHIFT_ID?'selected':''}>${esc(x.SHIFT_NAME)} ${esc(x.START_TIME)}-${esc(x.END_TIME)}</option>`).join('')}</select></label><label>Giờ bắt đầu<input name="START_TIME" value="${esc(row.START_TIME||'')}"></label><label>Giờ kết thúc<input name="END_TIME" value="${esc(row.END_TIME||'')}"></label><label class="full">Tên công việc<input name="TASK_TITLE" value="${esc(row.TASK_TITLE||'')}" required></label><label class="full">Ghi chú<textarea name="NOTE" rows="3">${esc(row.NOTE||'')}</textarea></label><div class="full"><b>Nhân viên được phân công</b><div class="checklist">${e.rows.filter(x=>x.STATUS==='ACTIVE').map(x=>`<label class="check"><input type="checkbox" name="EMPLOYEE_IDS" value="${esc(x.EMPLOYEE_ID)}">${esc(x.NAME)} · ${esc(x.EMPLOYEE_ID)}</label>`).join('')}</div></div></div>${formButtons('LƯU PHÂN CÔNG')}</form><div id="formMsg"></div>`);$('assignmentForm').onsubmit=async ev=>{ev.preventDefault();const fd=new FormData(ev.target),o={};fd.forEach((v,k)=>{if(k!=='EMPLOYEE_IDS')o[k]=String(v)});o.EMPLOYEE_IDS=fd.getAll('EMPLOYEE_IDS').map(String);try{await api('adminSaveAssignment',o);closeModal();admin('assignments')}catch(e){setMsg('formMsg',e.message,true)}}}
function showNotificationForm(){modal(`<h2>GỬI THÔNG BÁO</h2><form id="notificationForm"><div class="formgrid"><label>Nhân viên<input name="EMPLOYEE_ID" placeholder="EMPLOYEE_ID" required></label><label>Loại<input name="TYPE" value="INFO"></label><label class="full">Tiêu đề<input name="TITLE" required></label><label class="full">Nội dung<textarea name="MESSAGE" rows="4" required></textarea></label><label>REF_ID<input name="REF_ID"></label></div>${formButtons('GỬI')}</form><div id="formMsg"></div>`);$('notificationForm').onsubmit=async ev=>{ev.preventDefault();try{await api('adminNotifications',Object.assign(parseForm(ev.target),{send:true}));closeModal();admin('notifications')}catch(e){setMsg('formMsg',e.message,true)}}}
async function adminEvent(ev){const t=ev.target;if(t.matches('[data-new="employee"]'))return showEmployeeForm();if(t.matches('[data-edit-employees]')){const r=$('adminContent')._rows?.[Number(t.dataset.editEmployees)];if(r)return showEmployeeForm(r);return}if(t.matches('[data-edit-projects]')){const r=$('adminContent')._rows?.[Number(t.dataset.editProjects)];if(r)return showProjectForm(r);return}if(t.matches('[data-edit-shifts]')){const r=$('adminContent')._rows?.[Number(t.dataset.editShifts)];if(r)return showShiftForm(r);return}if(t.matches('[data-edit-groups]')){const r=$('adminContent')._rows?.[Number(t.dataset.editGroups)];if(r)return showGroupForm(r);return}if(t.matches('[data-new="project"]'))return showProjectForm();if(t.matches('[data-new="shift"]'))return showShiftForm();if(t.matches('[data-new="group"]'))return showGroupForm();if(t.matches('[data-new="assignment"]'))return showAssignmentForm();if(t.matches('[data-new="notification"]'))return showNotificationForm();if(t.matches('[data-approve]')){try{await api('approveAttendance',{ATTENDANCE_ID:t.dataset.approve,STATUS:t.dataset.status});admin('attendance')}catch(e){alert(e.message)}return}if(t.matches('[data-leave]')){try{await api('adminLeaveDecision',{LEAVE_ID:t.dataset.leave,STATUS:t.dataset.status});admin('leave')}catch(e){alert(e.message)}return}if(t.matches('[data-delete-assignment]')){if(!confirm('Xóa phân công này?'))return;try{await api('adminDeleteAssignment',{ASSIGNMENT_ID:t.dataset.deleteAssignment});admin('assignments')}catch(e){alert(e.message)}return}if(t.matches('[data-edit-assignment]')){const x=await api('adminAssignments');const r=(x.rows||[]).find(a=>String(a.ASSIGNMENT_ID)===String(t.dataset.editAssignment));if(r)showAssignmentForm(r);return}if(t.matches('[data-report-copy]')){const x=await api('adminReports',{month:monthNow()});csvDownload(x.rows,'CUATUNG_LIGHTING_BAO_CAO_'+x.month+'.csv');return}if(t.matches('[data-notification]')){try{await api('markNotificationRead',{NOTIFICATION_ID:t.dataset.notification});closeModal();await boot()}catch(e){alert(e.message)}return}if(t.matches('[data-close-modal]'))return closeModal();if(t.matches('[data-close-admin]'))return closeModal()}
updateConfigMessage();net();window.addEventListener('online',()=>{net();flushQueue()});window.addEventListener('offline',net);
$('loginBtn').onclick=login;$('in').onclick=()=>attendance('CHECKIN');$('out').onclick=()=>attendance('CHECKOUT');$('logout').onclick=logout;$('change').onclick=passwordModal;$('leaveBtn').onclick=leave;$('statsMonth').value=monthNow();$('statsMonth').onchange=renderStats;$('modal').addEventListener('click',adminEvent);$('adminContent').addEventListener('click',adminEvent);document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));document.querySelectorAll('[data-admin]').forEach(b=>b.onclick=()=>admin(b.dataset.admin));
$('phone').addEventListener('keydown',e=>{if(e.key==='Enter')$('password').focus()});$('password').addEventListener('keydown',e=>{if(e.key==='Enter')login()});
})();
