(()=>{'use strict';
let token='',me=null;
let S={projects:[],shifts:[],attendance:null,assignments:[],notifications:[]};
let screen='home',history=['home'],leaveDates=[];
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const API=()=>String(window.APP_CONFIG?.API_URL||'').trim();
const nowVN=()=>{const d=new Date(),z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z};
const today=()=>nowVN().toISOString().slice(0,10),monthNow=()=>today().slice(0,7);
const uid=()=>crypto.randomUUID?crypto.randomUUID():(Date.now()+'-'+Math.random());
function updateConfigMessage(){const e=$('configMsg');if(!e)return;if(API()){e.classList.add('hidden');e.textContent=''}else{e.classList.remove('hidden');e.textContent='Không đọc được API_URL từ config.js.'}}
function ensureApi(){if(!API())throw Error('API_URL chưa được nạp từ config.js.')}
async function api(action,payload={}){ensureApi();const r=await fetch(API(),{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},cache:'no-store',body:JSON.stringify({action,payload,token})});const x=await r.json().catch(()=>({ok:false,error:'Phản hồi máy chủ không hợp lệ.'}));if(!x.ok)throw Error(x.error||'API_ERROR');return x}
function setMsg(id,text,error=false){const e=$(id);if(!e)return;e.textContent=text||'';e.className=error?'err':'ok'}
function net(){const e=$('net');if(!e)return;e.textContent=navigator.onLine?'ONLINE':'OFFLINE';e.className='status '+(navigator.onLine?'':'off')}
function deviceId(){let x=localStorage.getItem('ct_device_id');if(!x){x=uid();localStorage.setItem('ct_device_id',x)}return x}
function qget(){try{return JSON.parse(localStorage.getItem('ct_offline_queue')||'[]')}catch{return[]}}
function qsave(q){localStorage.setItem('ct_offline_queue',JSON.stringify(q.slice(-100)))}
function nav(n,replace=false){if(screen===n&&!replace)return;history=replace?[n]:[...history.slice(0,history.indexOf(screen)+1),n];screen=n;renderScreen();}
function back(){if(history.length>1){history.pop();screen=history[history.length-1];renderScreen()}else nav('home',true)}
function renderScreen(){document.querySelectorAll('[data-screen]').forEach(e=>e.classList.toggle('hidden',e.dataset.screen!==(screen.startsWith('admin:')?'adminPanel':screen)));document.querySelectorAll('#tabs button').forEach(e=>e.classList.remove('active'));window.scrollTo({top:0,behavior:'instant'});if(screen==='attendance')renderAttendance();if(screen==='jobs')renderJobs();if(screen==='history')renderHistory();if(screen==='stats')renderStats();if(screen==='notifications')renderNotificationsScreen();if(screen==='leave')renderLeave();if(screen==='home')renderHome();if(screen==='adminHome')renderAdminHome();if(screen.startsWith('admin:'))admin(screen.slice(6))}
function header(){ $('login').classList.add('hidden');$('app').classList.remove('hidden');$('name').textContent=me?.NAME||'-';$('role').textContent=me?.ROLE==='ADMIN'?'QUẢN TRỊ VIÊN':'NHÂN VIÊN';$('adminTab').classList.toggle('hidden',me?.ROLE!=='ADMIN');$('force').classList.toggle('hidden',me?.FORCE_PASSWORD_CHANGE!=='YES');}
async function login(){const b=$('loginBtn');b.disabled=true;setMsg('msg','');try{const x=await api('login',{phone:$('phone').value,password:$('password').value});token=x.token;me=x.me;sessionStorage.setItem('ct_session_active','1');if($('remember').checked)localStorage.setItem('ct_login_phone',$('phone').value.replace(/\D/g,''));else localStorage.removeItem('ct_login_phone');await boot();if(x.forcePasswordChange)passwordModal()}catch(e){setMsg('msg',e.message,true)}finally{b.disabled=false}}
async function boot(){const x=await api('bootstrap');S={projects:x.projects||[],shifts:x.shifts||[],attendance:x.attendance||null,assignments:x.assignments||[],notifications:x.notifications||[]};me=x.me;header();history=['home'];screen=me.ROLE==='ADMIN'?'adminHome':'home';renderScreen();await unreadAfterLogin();flushQueue()}
async function unreadAfterLogin(){if(!S.notifications.length)return;const pending=S.notifications.slice();for(const n of pending){await showUnread(n)}await refreshNotifications()}
function showUnread(n){return new Promise(resolve=>{modal(`<div class="unread-notice"><div class="unread-icon">🔔</div><h2>${esc(n.TITLE)}</h2><p>${esc(n.MESSAGE)}</p><button class="primary" id="unreadView">XEM</button></div>`);$('unreadView').onclick=async()=>{try{await api('markNotificationRead',{NOTIFICATION_ID:n.NOTIFICATION_ID})}catch{}closeModal();resolve();};});}
async function refreshNotifications(){try{const x=await api('notificationsUser');S.notifications=(x.rows||[]).filter(n=>!n.READ_AT).slice(-30);renderBell()}catch{}}
function renderBell(){const b=$('bell');if(b)b.textContent=S.notifications.length?'🔔 '+S.notifications.length:'🔔'}
function renderHome(){renderBell()}
function renderAttendance(){const a=S.attendance,open=a&&String(a.STATE)==='OPEN',closed=a&&String(a.STATE)==='CLOSED';const inBtn=$('in'),outBtn=$('out');if(inBtn){inBtn.disabled=!!open||!!closed;inBtn.classList.toggle('hidden',!!open||!!closed)}if(outBtn){outBtn.disabled=!open;outBtn.classList.toggle('hidden',!open||!!closed)}$('state').textContent=closed?'ĐÃ HOÀN TẤT':open?'ĐÃ VÀO – CHỜ RA':'CHƯA VÀO';if(a?.PROJECT_ID)$('project').value=a.PROJECT_ID;nearestProject()}
async function nearestProject(){if(!S.projects.length||!navigator.geolocation)return;try{const c=await gps();let best=null;for(const p of S.projects){const d=dist(c.latitude,c.longitude,Number(p.LAT),Number(p.LNG));if(!best||d<best.d)best={p,d}}if(best&&!S.attendance)$('project').value=best.p.PROJECT_ID}catch{}}
function dist(a,b,c,d){const R=6371000,r=x=>x*Math.PI/180,dl=r(c-a),dn=r(d-b),z=Math.sin(dl/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(dn/2)**2;return R*2*Math.atan2(Math.sqrt(z),Math.sqrt(1-z))}
function renderJobs(){$('jobsList').innerHTML=S.assignments.length?S.assignments.map(x=>`<div class="row"><div><b>${esc(x.TASK_TITLE||'Công việc')}</b><small>${esc(x.START_TIME||'')} – ${esc(x.END_TIME||'')}</small><small>${esc(x.NOTE||'')}</small></div><span class="badge">${esc(x.STATUS||'ACTIVE')}</span></div>`).join(''):'<div class="empty">Chưa có công việc được phân công.</div>'}
async function renderHistory(){try{const x=await api('monthlyStats',{month:monthNow()});$('historyList').innerHTML=(x.records||[]).slice().reverse().slice(0,100).map(r=>`<div class="row"><div><b>${esc(r.WORK_DATE)}</b><small>${esc(r.PROJECT_ID||'-')} · ${esc(r.SHIFT_ID||'-')}</small><small>${esc(r.CHECKIN_TIME||'-')} → ${esc(r.CHECKOUT_TIME||'-')}</small></div><span class="badge">${esc(r.STATUS||'-')}</span></div>`).join('')||'<div class="empty">Chưa có dữ liệu.</div>'}catch(e){$('historyList').innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}
async function renderStats(){const m=$('statsMonth')?.value||monthNow(),mode=$('statsMode')?.value||'MONTH';try{if(mode==='DAY'){const d=$('statsDay')?.value||today();const x=await api('dailyStats',{date:d});$('statsGrid').innerHTML=dayTable(x);}else{const x=await api('monthlyStats',{month:m});$('statsGrid').innerHTML=`<div class="stats">${[['Ngày công',x.totalDays],['Giờ công',Number(x.totalHours||0).toFixed(2)],['Nghỉ phép',x.totalLeave],['Đi muộn',x.late],['Về sớm',x.early]].map(a=>`<div class="stat"><small>${a[0]}</small><b>${a[1]}</b></div>`).join('')}</div>${table(x.records||[],['WORK_DATE','PROJECT_ID','SHIFT_ID','CHECKIN_TIME','CHECKOUT_TIME','WORK_HOURS','STATUS'])}`;}}catch(e){$('statsGrid').innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}
function dayTable(x){return `${table(x.attendance||[],['WORK_DATE','PROJECT_ID','SHIFT_ID','CHECKIN_TIME','CHECKOUT_TIME','WORK_HOURS','STATUS'])}${table(x.leave||[],['WORK_DATE','TYPE','SHIFT','REASON','STATUS'])}`}
function renderLeave(){const list=$('leaveDatesList');if(list)list.innerHTML=leaveDates.length?leaveDates.map(d=>`<span class="date-chip">${esc(d)} <button type="button" data-remove-date="${esc(d)}">×</button></span>`).join(''):'<span class="muted">Chưa chọn ngày.</span>'}
async function leave(){try{if(!leaveDates.length)throw Error('Chọn ít nhất một ngày.');const type=$('leaveType').value;await api('leaveRequest',{DATES:leaveDates,TYPE:type,SHIFT:type,REASON:$('leaveReason').value});leaveDates=[];renderLeave();setMsg('leaveMsg','Đã gửi đề nghị nghỉ.')}catch(e){setMsg('leaveMsg',e.message,true)}}
function addLeaveDate(){const d=$('leaveDate').value;if(d&&!leaveDates.includes(d))leaveDates.push(d);renderLeave()}
function renderNotificationsScreen(){api('notificationsUser').then(x=>{$('notificationsList').innerHTML=(x.rows||[]).slice().reverse().map(n=>`<div class="row"><div><b>${esc(n.TITLE)}</b><small>${esc(n.CREATED_AT||'')}</small><small>${esc(n.MESSAGE)}</small></div><span class="badge">${n.READ_AT?'ĐÃ XEM':'CHƯA XEM'}</span></div>`).join('')||'<div class="empty">Chưa có thông báo.</div>'}).catch(e=>$('notificationsList').innerHTML=esc(e.message))}
function gps(){return new Promise((ok,no)=>navigator.geolocation.getCurrentPosition(p=>ok(p.coords),e=>no(Error('Không lấy được GPS: '+e.message)),{enableHighAccuracy:true,timeout:15000,maximumAge:0}))}
async function attendance(action){const msg=$('attMsg');msg.textContent='Đang lấy vị trí...';try{const c=await gps();const ev={eventId:uid(),action,PROJECT_ID:$('project').value,eventTime:new Date().toISOString(),lat:c.latitude,lng:c.longitude,accuracy:c.accuracy,deviceId:deviceId()};if(!navigator.onLine){if(!token)throw Error('Cần đăng nhập online trước khi chấm công offline.');const q=qget();q.push(ev);qsave(q);msg.textContent=action==='CHECKIN'?'Đã ghi VÀO offline.':'Đã ghi RA offline.';if(action==='CHECKIN'){S.attendance={STATE:'OPEN',PROJECT_ID:ev.PROJECT_ID};renderAttendance()}else{S.attendance={STATE:'CLOSED',PROJECT_ID:ev.PROJECT_ID};renderAttendance()}return}const r=await api(action==='CHECKIN'?'checkinPreview':'checkoutPreview',ev);if(r.duplicate){await boot();msg.textContent='Bản ghi đã tồn tại.';return}await api('commitPreview',{previewToken:r.previewToken});await boot();msg.textContent=action==='CHECKIN'?'VÀO CA THÀNH CÔNG':'RA CA THÀNH CÔNG'}catch(e){msg.textContent=e.message}}
async function flushQueue(){if(!navigator.onLine||!token)return;const q=qget();if(!q.length)return;try{const r=await api('syncEvents',{events:q});const failed=(r.results||[]).filter(x=>!x.ok);const bad=new Set(failed.map(x=>String(x.eventId)));qsave(q.filter(e=>bad.has(String(e.eventId))));if(!failed.length){await boot()}}catch{}}
function passwordModal(){modal(`<h2>ĐỔI MẬT KHẨU</h2><p class="muted">Mật khẩu mới tối thiểu 8 ký tự.</p><label>Mật khẩu mới<input id="np" type="password" minlength="8"></label><label>Xác nhận<input id="np2" type="password"></label><div id="pm"></div><div class="actions"><button class="secondary" data-close-modal>HỦY</button><button class="primary" id="ps">LƯU</button></div>`);$('ps').onclick=async()=>{if($('np').value.length<8||$('np').value!==$('np2').value){setMsg('pm','Mật khẩu không hợp lệ.',true);return}try{await api('changePassword',{newPassword:$('np').value});closeModal();me.FORCE_PASSWORD_CHANGE='NO';$('force').classList.add('hidden')}catch(e){setMsg('pm',e.message,true)}}}
function modal(html){$('modal').innerHTML='<div>'+html+'</div>';$('modal').classList.remove('hidden')}
function closeModal(){$('modal').classList.add('hidden');$('modal').innerHTML=''}
async function logout(){try{await api('logout')}catch{}token='';me=null;sessionStorage.removeItem('ct_session_active');location.reload()}
function table(rows,cols){if(!rows?.length)return '<div class="empty">Không có dữ liệu.</div>';return '<div class="table"><table><thead><tr>'+cols.map(c=>`<th>${esc(c)}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>`<td>${esc(r[c]??'')}</td>`).join('')+'</tr>').join('')+'</tbody></table></div>'}
function formButtons(label='LƯU'){return `<div class="form-actions"><button class="secondary" type="button" data-close-modal>HỦY</button><button class="primary" type="submit">${label}</button></div>`}
function parseForm(f){const o={};new FormData(f).forEach((v,k)=>{o[k]=String(v)});return o}
function adminList(rows,kind){if(!rows?.length)return '<div class="empty">Không có dữ liệu.</div>';return rows.map((r,i)=>{let title='',sub='';if(kind==='employees'){title=`${esc(r.NAME)} · ${esc(r.EMPLOYEE_ID)}`;sub=`${esc(r.PHONE)} · ${esc(r.ROLE)} · ${esc(r.STATUS)}`}if(kind==='projects'){title=`${esc(r.PROJECT_NAME)} · ${esc(r.PROJECT_ID)}`;sub=`${esc(r.ADDRESS||'')} · ${esc(r.LAT)}, ${esc(r.LNG)} · ${esc(r.RADIUS_M)}m · ${esc(r.STATUS)}`}if(kind==='shifts'){title=`${esc(r.SHIFT_NAME)} · ${esc(r.SHIFT_ID)}`;sub=`${esc(r.START_TIME)} – ${esc(r.END_TIME)} · sớm ${esc(r.EARLY_TOL_MIN)}p · trễ ${esc(r.LATE_TOL_MIN)}p · ${esc(r.STATUS)}`}if(kind==='groups'){title=`${esc(r.GROUP_NAME)} · ${esc(r.GROUP_ID)}`;sub=`Trưởng nhóm: ${esc(r.LEADER_ID||'-')} · ${esc(r.STATUS)}`}return `<div class="row"><div><b>${title}</b><small>${sub}</small></div><div class="row-actions"><button class="mini" data-edit-kind="${kind}" data-index="${i}">Sửa</button>${kind==='employees'?`<button class="mini" data-reset-password="${esc(r.EMPLOYEE_ID)}">Reset MK</button>`:''}</div></div>`}).join('')}
async function renderAdminHome(){const x=await api('adminDashboard');$('adminDash').innerHTML=`<div class="stats">${[['Nhân viên',x.activeUsers],['Chờ duyệt',x.pendingAttendance],['Công trình',x.projects],['Nhóm',x.groups]].map(a=>`<div class="stat"><small>${a[0]}</small><b>${a[1]}</b></div>`).join('')}</div>`}
async function admin(kind){
 const box=$('adminContent');box.innerHTML='<div class="empty">Đang tải...</div>';
 try{
  if(kind==='dashboard'){const x=await api('adminDashboard');box.innerHTML='<h2>TỔNG QUAN</h2><div class="stats">'+[['Nhân viên',x.activeUsers],['Chờ duyệt',x.pendingAttendance],['Công trình',x.projects],['Nhóm',x.groups]].map(a=>'<div class="stat"><small>'+a[0]+'</small><b>'+a[1]+'</b></div>').join('')+'</div>';return;}
  if(kind==='employees'){const x=await api('adminEmployees');box.innerHTML='<div class="admin-title"><h2>NHÂN VIÊN</h2><button class="secondary" data-new="employee">＋ Thêm</button></div>'+adminList(x.rows,'employees');box._rows=x.rows;return;}
  if(kind==='projects'){const x=await api('adminProjects');box.innerHTML='<div class="admin-title"><h2>CÔNG TRÌNH</h2><button class="secondary" data-new="project">＋ Thêm</button></div>'+adminList(x.rows,'projects');box._rows=x.rows;return;}
  if(kind==='shifts'){const x=await api('adminShifts');box.innerHTML='<div class="admin-title"><h2>CA LÀM</h2><button class="secondary" data-new="shift">＋ Thêm</button></div>'+adminList(x.rows,'shifts');box._rows=x.rows;return;}
  if(kind==='groups'){const x=await api('adminGroups');box.innerHTML='<div class="admin-title"><h2>NHÓM LÀM VIỆC</h2><button class="secondary" data-new="group">＋ Thêm</button></div>'+adminList(x.rows,'groups');box._rows=x.rows;return;}
  if(kind==='attendance'){
   const x=await api('adminAttendance',{month:monthNow(),status:'PENDING'});const rows=(x.rows||[]).filter(r=>String(r.STATUS)==='PENDING');
   const list=rows.map(r=>'<div class="row"><div><b>'+esc(r.EMPLOYEE_ID)+' · '+esc(r.WORK_DATE)+'</b><small>'+esc(r.CHECKIN_TIME||'')+' → '+esc(r.CHECKOUT_TIME||'')+'</small></div><div class="row-actions"><button class="mini" data-approve="'+esc(r.ATTENDANCE_ID)+'" data-status="APPROVED">Duyệt</button><button class="mini danger" data-approve="'+esc(r.ATTENDANCE_ID)+'" data-status="REJECTED">Từ chối</button></div></div>').join('');
   box.innerHTML='<div class="admin-title"><h2>DUYỆT CÔNG</h2></div>'+(list||'<div class="empty">Không có công chờ duyệt.</div>');return;
  }
  if(kind==='makeup'){
   const [e,p,s]=await Promise.all([api('adminEmployees'),api('adminProjects'),api('adminShifts')]);const employees=(e.rows||[]).filter(r=>r.STATUS==='ACTIVE'),projects=(p.rows||[]).filter(r=>r.STATUS!=='INACTIVE'),shifts=(s.rows||[]).filter(r=>r.STATUS!=='INACTIVE');
   box.innerHTML='<h2>CHẤM CA BÙ</h2><form id="makeupForm"><div class="formgrid"><label>Nhân viên<select name="EMPLOYEE_ID">'+employees.map(r=>'<option value="'+esc(r.EMPLOYEE_ID)+'">'+esc(r.NAME)+' · '+esc(r.EMPLOYEE_ID)+'</option>').join('')+'</select></label><label>Ngày<input name="WORK_DATE" type="date" value="'+today()+'" required></label><label>Công trình<select name="PROJECT_ID">'+projects.map(r=>'<option value="'+esc(r.PROJECT_ID)+'">'+esc(r.PROJECT_NAME)+'</option>').join('')+'</select></label><label>Ca bù<select name="SHIFT_PART"><option value="SANG">Sáng</option><option value="CHIEU">Chiều</option><option value="TOI">Tối</option><option value="NGAY">Ngày</option></select></label><input type="hidden" name="SHIFT_ID" value="'+esc(shifts[0]?.SHIFT_ID||'')+'"><label class="full">Lý do<textarea name="REASON" required></textarea></label></div>'+formButtons('TẠO PHIẾU')+'</form>';
   $('makeupForm').onsubmit=async e=>{e.preventDefault();try{await api('adminMakeup',parseForm(e.target));admin('makeup')}catch(err){alert(err.message)}};return;
  }
  if(kind==='assignments'){
   const x=await api('adminAssignments');const list=(x.rows||[]).map(r=>'<div class="row"><div><b>'+esc(r.TASK_TITLE)+'</b><small>'+esc(r.WORK_DATE)+' · '+esc(r.PROJECT_ID)+' · '+esc(r.SHIFT_ID)+'</small><small>'+esc(r.NOTE||'')+'</small></div><div class="row-actions"><button class="mini" data-edit-assignment="'+esc(r.ASSIGNMENT_ID)+'">Sửa</button><button class="mini danger" data-delete-assignment="'+esc(r.ASSIGNMENT_ID)+'">Xóa</button></div></div>').join('');
   box.innerHTML='<div class="admin-title"><h2>PHÂN CÔNG</h2><button class="secondary" data-new="assignment">＋ Tạo</button></div>'+(list||'<div class="empty">Chưa có phân công.</div>');return;
  }
  if(kind==='leave'){
   const x=await api('adminLeave',{STATUS:'PENDING'});const list=(x.rows||[]).map(r=>'<div class="row"><div><b>'+esc(r.EMPLOYEE_ID)+' · '+esc(r.WORK_DATE)+'</b><small>'+esc(r.TYPE)+' · '+esc(r.REASON)+'</small></div><div class="row-actions"><button class="mini" data-leave="'+esc(r.LEAVE_ID)+'" data-status="APPROVED">Duyệt</button><button class="mini danger" data-leave="'+esc(r.LEAVE_ID)+'" data-status="REJECTED">Từ chối</button></div></div>').join('');
   box.innerHTML='<h2>NGHỈ PHÉP CHỜ DUYỆT</h2>'+(list||'<div class="empty">Không có đề nghị chờ.</div>');return;
  }
  if(kind==='notifications'){const x=await api('adminNotifications');box.innerHTML='<div class="admin-title"><h2>THÔNG BÁO</h2><button class="secondary" data-new="notification">＋ Gửi</button></div>'+table(x.rows||[],['EMPLOYEE_ID','TITLE','MESSAGE','CREATED_AT','READ_AT']);return;}
  if(kind==='logs'){const x=await api('adminLogs');box.innerHTML='<h2>NHẬT KÝ</h2>'+table(x.rows||[],['TIME','ACTION','USER_ID','DETAIL']);return;}
  if(kind==='reports'){await reportScreen(box);return;}
 }catch(e){box.innerHTML='<div class="err">'+esc(e.message)+'</div>';}
}
async function reportScreen(box){const e=await api('adminEmployees');box.innerHTML=`<h2>BÁO CÁO</h2><div class="formgrid"><label>Loại<select id="reportType"><option value="MONTH">THÁNG</option><option value="DAY">NGÀY</option></select></label><label>Nhân viên<select id="reportEmployee"><option value="ALL">Tất cả</option>${e.rows.filter(x=>x.STATUS!=='INACTIVE').map(x=>`<option value="${esc(x.EMPLOYEE_ID)}">${esc(x.NAME)} · ${esc(x.EMPLOYEE_ID)}</option>`).join('')}</select></label><label id="reportMonthWrap">Tháng<input id="reportMonth" type="month" value="${monthNow()}"></label><label id="reportDateWrap" class="hidden">Ngày<input id="reportDate" type="date" value="${today()}"></label></div><div class="actions"><button class="secondary" id="reportLoad">XEM</button><button class="secondary" id="reportExcel">XUẤT EXCEL</button><button class="primary" id="reportPdf">XUẤT PDF</button></div><div id="reportOut"></div>`;const load=async()=>{const type=$('reportType').value,x=await api('adminReports',{type,employeeId:$('reportEmployee').value,month:$('reportMonth').value,date:$('reportDate').value});const headers=Array.from({length:8},(_,i)=>x.header?.find?.(h=>h.KEY==='HEADER_'+(i+1))?.VALUE||'');$('reportOut').innerHTML='<div id="printReport">'+headers.map((h,i)=>'<div class="report-header-line">'+esc(h)+'</div>').join('')+(table(x.rows||[],type==='DAY'?['EMPLOYEE_ID','NAME','WORK_DATE','PROJECT_ID','SHIFT_ID','CHECKIN_TIME','CHECKOUT_TIME','WORK_HOURS','STATUS']:['EMPLOYEE_ID','NAME','WORK_DAYS','WORK_HOURS','LEAVE','LATE','EARLY','RECORDS','PENDING']))+'</div>';return x};$('reportType').onchange=()=>{const d=$('reportType').value==='DAY';$('reportMonthWrap').classList.toggle('hidden',d);$('reportDateWrap').classList.toggle('hidden',!d)};$('reportLoad').onclick=load;$('reportExcel').onclick=async()=>{const x=await load();downloadExcel(x.rows,'CUATUNG_LIGHTING_BAO_CAO.xls')};$('reportPdf').onclick=async()=>{await load();window.print()};await load()}
function downloadExcel(rows,name){const cols=rows.length?Object.keys(rows[0]):[];const html='<table><tr>'+cols.map(c=>`<th>${esc(c)}</th>`).join('')+'</tr>'+rows.map(r=>'<tr>'+cols.map(c=>`<td>${esc(r[c]??'')}</td>`).join('')+'</tr>').join('')+'</table>';const b=new Blob([`<html><meta charset="utf-8">${html}</html>`],{type:'application/vnd.ms-excel'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function showEmployeeForm(row={}){modal(`<h2>${row.EMPLOYEE_ID?'SỬA':'THÊM'} NHÂN VIÊN</h2><form id="employeeForm"><div class="formgrid"><label>Mã nhân viên<input name="EMPLOYEE_ID" value="${esc(row.EMPLOYEE_ID||'')}" required ${row.EMPLOYEE_ID?'readonly':''}></label><label>Họ tên<input name="NAME" value="${esc(row.NAME||'')}" required></label><label>Số điện thoại<input name="PHONE" inputmode="tel" value="${esc(row.PHONE||'')}" required></label><label>Vai trò<select name="ROLE"><option ${row.ROLE==='USER'?'selected':''}>USER</option><option ${row.ROLE==='ADMIN'?'selected':''}>ADMIN</option></select></label><label>Trạng thái<select name="STATUS"><option ${row.STATUS!=='INACTIVE'?'selected':''}>ACTIVE</option><option ${row.STATUS==='INACTIVE'?'selected':''}>INACTIVE</option></select></label><label>${row.EMPLOYEE_ID?'Mật khẩu mới':'Mật khẩu ban đầu'}<input name="password" type="password" minlength="8" ${row.EMPLOYEE_ID?'':'required'}></label></div><p class="muted">Tài khoản mới hoặc đổi mật khẩu sẽ buộc đổi mật khẩu lần sau.</p>${formButtons()}</form><div id="formMsg"></div>`);$('employeeForm').onsubmit=async e=>{e.preventDefault();try{await api('adminSaveEmployee',parseForm(e.target));closeModal();admin('employees')}catch(err){setMsg('formMsg',err.message,true)}}}
function showProjectForm(row={}){modal(`<h2>${row.PROJECT_ID?'SỬA':'THÊM'} CÔNG TRÌNH</h2><form id="projectForm"><div class="formgrid"><label>Mã công trình<input name="PROJECT_ID" value="${esc(row.PROJECT_ID||'')}" required></label><label>Tên công trình<input name="PROJECT_NAME" value="${esc(row.PROJECT_NAME||'')}" required></label><label class="full">Địa chỉ<input name="ADDRESS" value="${esc(row.ADDRESS||'')}"></label><label class="full">Tọa độ Google Maps<input name="COORDINATES" value="${row.LAT&&row.LNG?esc(row.LAT+', '+row.LNG):''}" placeholder="16.467812, 107.590421" required></label><label>Bán kính (m)<input name="RADIUS_M" type="number" min="10" value="${esc(row.RADIUS_M||100)}"></label><label>Trạng thái<select name="STATUS"><option ${row.STATUS!=='INACTIVE'?'selected':''}>ACTIVE</option><option ${row.STATUS==='INACTIVE'?'selected':''}>INACTIVE</option></select></label></div>${formButtons()}</form><div id="formMsg"></div>`);$('projectForm').onsubmit=async e=>{e.preventDefault();try{await api('adminSaveProject',parseForm(e.target));closeModal();admin('projects')}catch(err){setMsg('formMsg',err.message,true)}}}
function showShiftForm(row={}){modal(`<h2>${row.SHIFT_ID?'SỬA':'THÊM'} CA LÀM</h2><form id="shiftForm"><div class="formgrid"><label>Mã ca<input name="SHIFT_ID" value="${esc(row.SHIFT_ID||'')}" required></label><label>Tên ca<input name="SHIFT_NAME" value="${esc(row.SHIFT_NAME||'')}" required></label><label>Giờ bắt đầu<input name="START_TIME" type="time" value="${esc(row.START_TIME||'')}" required></label><label>Giờ kết thúc<input name="END_TIME" type="time" value="${esc(row.END_TIME||'')}" required></label><label>Cho phép vào sớm (phút)<input name="EARLY_TOL_MIN" type="number" min="0" value="${esc(row.EARLY_TOL_MIN||0)}"></label><label>Cho phép trễ (phút)<input name="LATE_TOL_MIN" type="number" min="0" value="${esc(row.LATE_TOL_MIN||15)}"></label><label>Trạng thái<select name="STATUS"><option ${row.STATUS!=='INACTIVE'?'selected':''}>ACTIVE</option><option ${row.STATUS==='INACTIVE'?'selected':''}>INACTIVE</option></select></label></div>${formButtons()}</form><div id="formMsg"></div>`);$('shiftForm').onsubmit=async e=>{e.preventDefault();try{await api('adminSaveShift',parseForm(e.target));closeModal();admin('shifts')}catch(err){setMsg('formMsg',err.message,true)}}}
function showGroupForm(row={}){modal(`<h2>${row.GROUP_ID?'SỬA':'THÊM'} NHÓM</h2><form id="groupForm"><div class="formgrid"><label>Mã nhóm<input name="GROUP_ID" value="${esc(row.GROUP_ID||'')}" required></label><label>Tên nhóm<input name="GROUP_NAME" value="${esc(row.GROUP_NAME||'')}" required></label><label>Trưởng nhóm<input name="LEADER_ID" value="${esc(row.LEADER_ID||'')}"></label><label>Trạng thái<select name="STATUS"><option>ACTIVE</option><option ${row.STATUS==='INACTIVE'?'selected':''}>INACTIVE</option></select></label></div>${formButtons()}</form><div id="formMsg"></div>`);$('groupForm').onsubmit=async e=>{e.preventDefault();try{await api('adminSaveGroup',parseForm(e.target));closeModal();admin('groups')}catch(err){setMsg('formMsg',err.message,true)}}}
async function showAssignmentForm(row={}){const [g,p,s,e]=await Promise.all([api('adminGroups'),api('adminProjects'),api('adminShifts'),api('adminEmployees')]);modal(`<h2>${row.ASSIGNMENT_ID?'SỬA':'TẠO'} PHÂN CÔNG</h2><form id="assignmentForm"><input type="hidden" name="ASSIGNMENT_ID" value="${esc(row.ASSIGNMENT_ID||'')}"><div class="formgrid"><label>Ngày<input name="WORK_DATE" type="date" value="${esc(row.WORK_DATE||today())}" required></label><label>Nhóm<select name="GROUP_ID">${g.rows.map(x=>`<option value="${esc(x.GROUP_ID)}" ${x.GROUP_ID===row.GROUP_ID?'selected':''}>${esc(x.GROUP_NAME)}</option>`).join('')}</select></label><label>Công trình<select name="PROJECT_ID">${p.rows.map(x=>`<option value="${esc(x.PROJECT_ID)}" ${x.PROJECT_ID===row.PROJECT_ID?'selected':''}>${esc(x.PROJECT_NAME)}</option>`).join('')}</select></label><label>Ca<select name="SHIFT_ID">${s.rows.map(x=>`<option value="${esc(x.SHIFT_ID)}" ${x.SHIFT_ID===row.SHIFT_ID?'selected':''}>${esc(x.SHIFT_NAME)}</option>`).join('')}</select></label><label>Giờ bắt đầu<input name="START_TIME" value="${esc(row.START_TIME||'')}"></label><label>Giờ kết thúc<input name="END_TIME" value="${esc(row.END_TIME||'')}"></label><label class="full">Tên công việc<input name="TASK_TITLE" value="${esc(row.TASK_TITLE||'')}" required></label><label class="full">Ghi chú<textarea name="NOTE" rows="3">${esc(row.NOTE||'')}</textarea></label><div class="full"><b>Nhân viên được phân công</b><div class="checklist">${e.rows.filter(x=>x.STATUS==='ACTIVE').map(x=>`<label class="check"><input type="checkbox" name="EMPLOYEE_IDS" value="${esc(x.EMPLOYEE_ID)}">${esc(x.NAME)} · ${esc(x.EMPLOYEE_ID)}</label>`).join('')}</div></div></div>${formButtons('LƯU PHÂN CÔNG')}</form><div id="formMsg"></div>`);$('assignmentForm').onsubmit=async ev=>{ev.preventDefault();const fd=new FormData(ev.target),o={};fd.forEach((v,k)=>{if(k!=='EMPLOYEE_IDS')o[k]=String(v)});o.EMPLOYEE_IDS=fd.getAll('EMPLOYEE_IDS').map(String);try{await api('adminSaveAssignment',o);closeModal();admin('assignments')}catch(e){setMsg('formMsg',e.message,true)}}}
function showNotificationForm(){modal(`<h2>GỬI THÔNG BÁO</h2><form id="notificationForm"><div class="formgrid"><label>Nhân viên<input name="EMPLOYEE_ID" required></label><label>Loại<input name="TYPE" value="INFO"></label><label class="full">Tiêu đề<input name="TITLE" required></label><label class="full">Nội dung<textarea name="MESSAGE" rows="4" required></textarea></label><label>REF_ID<input name="REF_ID"></label></div>${formButtons('GỬI')}</form><div id="formMsg"></div>`);$('notificationForm').onsubmit=async e=>{e.preventDefault();try{await api('adminNotifications',Object.assign(parseForm(e.target),{send:true}));closeModal();admin('notifications')}catch(err){setMsg('formMsg',err.message,true)}}}
async function adminEvent(ev){const t=ev.target;if(t.matches('[data-new="employee"]'))return showEmployeeForm();if(t.matches('[data-new="project"]'))return showProjectForm();if(t.matches('[data-new="shift"]'))return showShiftForm();if(t.matches('[data-new="group"]'))return showGroupForm();if(t.matches('[data-new="assignment"]'))return showAssignmentForm();if(t.matches('[data-new="notification"]'))return showNotificationForm();if(t.matches('[data-edit-kind]')){const rows=$('adminContent')._rows||[];const r=rows[Number(t.dataset.index)];if(t.dataset.editKind==='employees')return showEmployeeForm(r);if(t.dataset.editKind==='projects')return showProjectForm(r);if(t.dataset.editKind==='shifts')return showShiftForm(r);if(t.dataset.editKind==='groups')return showGroupForm(r)}if(t.matches('[data-approve]')){try{await api('approveAttendance',{ATTENDANCE_ID:t.dataset.approve,STATUS:t.dataset.status});admin('attendance')}catch(e){alert(e.message)}return}if(t.matches('[data-leave]')){try{await api('adminLeaveDecision',{LEAVE_ID:t.dataset.leave,STATUS:t.dataset.status});admin('leave')}catch(e){alert(e.message)}return}if(t.matches('[data-delete-assignment]')){if(!confirm('Xóa phân công này?'))return;try{await api('adminDeleteAssignment',{ASSIGNMENT_ID:t.dataset.deleteAssignment});admin('assignments')}catch(e){alert(e.message)}return}if(t.matches('[data-edit-assignment]')){const x=await api('adminAssignments');const r=(x.rows||[]).find(a=>String(a.ASSIGNMENT_ID)===String(t.dataset.editAssignment));if(r)showAssignmentForm(r);return}if(t.matches('[data-close-modal]'))return closeModal();if(t.matches('[data-remove-date]')){leaveDates=leaveDates.filter(d=>d!==t.dataset.removeDate);renderLeave();return}if(t.matches('[data-reset-password]')){const pw=prompt('Nhập mật khẩu mới (tối thiểu 8 ký tự):');if(!pw)return;try{await api('adminResetPassword',{EMPLOYEE_ID:t.dataset.resetPassword,password:pw});alert('Đã đặt lại mật khẩu.')}catch(e){alert(e.message)}}}
const savedPhone=localStorage.getItem('ct_login_phone');if(savedPhone)$('phone').value=savedPhone;updateConfigMessage();net();window.addEventListener('online',()=>{net();flushQueue()});window.addEventListener('offline',net);
$('loginBtn').onclick=login;$('in').onclick=()=>attendance('CHECKIN');$('out').onclick=()=>attendance('CHECKOUT');$('logout').onclick=logout;$('change').onclick=passwordModal;$('leaveBtn').onclick=leave;$('addLeaveDate').onclick=addLeaveDate;$('statsMonth').value=monthNow();$('statsDay').value=today();$('statsMode').onchange=renderStats;$('statsMonth').onchange=renderStats;$('statsDay').onchange=renderStats;$('bell').onclick=()=>nav('notifications');$('backBtn').onclick=back;$('adminBackBtn').onclick=back;
$('password').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('phone').addEventListener('keydown',e=>{if(e.key==='Enter')$('password').focus()});
document.addEventListener('click',e=>{const t=e.target.closest('[data-nav]');if(t)nav(t.dataset.nav);const a=e.target.closest('[data-admin-nav]');if(a)nav('admin:'+a.dataset.adminNav);});$('adminContent').addEventListener('click',adminEvent);$('modal').addEventListener('click',adminEvent);
window.addEventListener('popstate',back);
renderScreen();
})();
