(()=>{'use strict';
const A=window.APP_CONFIG||{};const LS=window.localStorage;const SS=window.sessionStorage;let token=LS.getItem('cl_token')||SS.getItem('cl_token')||'';let me=readUser();let S={projects:[],shifts:[],attendance:[],assignments:[],unread:[],notifications:[]};let screen='login';
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function readUser(){try{return JSON.parse(LS.getItem('cl_me')||SS.getItem('cl_me')||'null')}catch(e){return null}}
function localDate(d=new Date()){const p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`}
function localMonth(){return localDate().slice(0,7)}
function localTime(){return new Date().toISOString()}
function setNet(ok){const e=$('netState');if(!e)return;e.textContent=ok?'ONLINE':'OFFLINE';e.classList.toggle('offline',!ok);e.classList.remove('ready')}
function toast(m){const e=$('toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),3200)}
let restoringHistory=false;
function page(html){$('app').innerHTML=html;window.scrollTo(0,0)}
function goBack(){
  if(me&&me.ROLE==='ADMIN') renderAdminHome(); else renderUserHome();
}
window.addEventListener('popstate',()=>{goBack()});

const readActions=new Set(['health','bootstrap','notificationsUser','userHistory','dailyStats','monthlyStats','adminDashboard','adminEmployees','adminPeople','adminProjects','adminShifts','adminAttendance','adminGroups','adminAssignments','adminLeave','adminNotifications','adminReports']);const inflight=new Map();
async function api(action,payload={}){if(readActions.has(action)){const k=action+'|'+JSON.stringify(payload||{});if(inflight.has(k))return inflight.get(k);const p=apiRequest(action,payload);inflight.set(k,p);try{return await p}finally{inflight.delete(k)}}return apiRequest(action,payload)}
async function apiRequest(action,payload={}){
  if(!A.API_URL)throw Error('Thiếu API_URL trong config.js.');
  const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),12000);
  try{const r=await fetch(A.API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,payload,token,clientVersion:A.VERSION}),signal:ctl.signal,cache:'no-store',credentials:'omit'});const raw=await r.text();let j;try{j=JSON.parse(raw)}catch(e){throw Error('Web App không trả JSON. Kiểm tra Deployment Web App và quyền Bất kỳ ai.')}if(!j.ok)throw Error(j.error||'API lỗi');if(j.version&&A.VERSION&&String(j.version)!==String(A.VERSION))throw Error('PHIÊN BẢN KHÔNG ĐỒNG BỘ: Ứng dụng '+A.VERSION+' / Máy chủ '+j.version+'. Hãy cập nhật đồng bộ Apps Script và GitHub.');setNet(true);return j}catch(e){if(e.name==='AbortError')throw Error('Máy chủ chưa phản hồi. Vui lòng thử lại sau vài giây.');if(e instanceof TypeError)throw Error('Không kết nối được Web App Google Apps Script.');throw e}finally{clearTimeout(timer)}}
function applyBootstrap(j){if(!j)return;S.projects=j.projects||[];S.shifts=j.shifts||[];S.attendance=j.attendance||[];S.assignments=j.assignments||[];S.unread=j.unread||[];S.notifications=(j.notifications||S.notifications||[]);me=j.me||me;saveSession()}
function saveSnapshot(j){try{LS.setItem('cl_bootstrap',JSON.stringify({at:Date.now(),data:j}))}catch(e){}}
function readSnapshot(){try{const x=JSON.parse(LS.getItem('cl_bootstrap')||'null');return x&&x.data?x:null}catch(e){return null}}
function clearSnapshot(){LS.removeItem('cl_bootstrap')}
function saveSession(){if(!token||!me)return;LS.setItem('cl_token',token);LS.setItem('cl_me',JSON.stringify(me));LS.setItem('cl_phone',me.PHONE||'')}
function setPowerVisible(show){const b=$('topPower');if(b)b.classList.toggle('hidden',!show)}
function clearSession(){token='';me=null;LS.removeItem('cl_token');LS.removeItem('cl_me');SS.removeItem('cl_token');SS.removeItem('cl_me');clearSnapshot();setPowerVisible(false)}
function renderLogin(status='Sẵn sàng đăng nhập'){screen='login';setPowerVisible(false);page(`<section class="screen wrap login-screen"><div class="login"><img class="login-logo" src="assets/logo.png" alt="Cuatung Lighting"><div class="login-heading"><h1 class="title">QUẢN LÝ CHẤM CÔNG</h1><div class="company-name">Cuatung Lighting</div></div><form id="loginForm"><div class="field"><label>Số điện thoại</label><input id="phone" inputmode="tel" autocomplete="username" value="${esc(LS.getItem('cl_phone')||'')}" required></div><div class="field"><label>Mật khẩu</label><input id="password" type="password" autocomplete="current-password" required></div><button id="loginBtn" class="btn primary full" type="submit">ĐĂNG NHẬP</button><p id="loginStatus" class="helper">${esc(status)}</p></form></div></section>`);$('loginForm').onsubmit=doLogin}
async function doLogin(e){
  e.preventDefault();const b=$('loginBtn'),st=$('loginStatus');b.disabled=true;st.textContent='Đang xác thực…';
  try{const j=await api('login',{phone:$('phone').value,password:$('password').value});token=j.token;me=j.me;saveSession();if(j.forcePasswordChange){showChangePassword(true);return}showHome();st.textContent='Đăng nhập thành công.';setNet(true);bootstrap().then(()=>{saveSnapshot(S);showUnread();syncQueue()}).catch(err=>{toast('Đang tải dữ liệu nền…');setNet(false)})}catch(err){st.textContent='LỖI: '+err.message;setNet(false)}finally{b.disabled=false}}
async function bootstrap(){const j=await api('bootstrap');applyBootstrap(j);saveSnapshot(j);return j}

function showHome(){setPowerVisible(!!me);if(me&&me.ROLE==='ADMIN')renderAdminHome();else renderUserHome()}
function backHome(){showHome()}
function renderUserHome(){screen='userHome';page(`<section class="screen wrap"><div class="home-head"><div><div class="user-name">${esc(me?.NAME||'')}</div><div class="user-role">NHÂN VIÊN</div></div><div class="icon-actions"><button class="icon-btn" onclick="renderNotifications()">🔔</button></div></div><div class="grid">${menu('📍','CHẤM CÔNG','VÀO / RA CA','renderAttendance()')}${menu('📊','THỐNG KÊ CÔNG / PHÉP','NGÀY / THÁNG','renderStats()')}${menu('📋','CÔNG VIỆC','PHÂN CÔNG CỦA TÔI','renderWork()')}${menu('📝','BÁO PHÉP','NHIỀU NGÀY / CA','renderLeave()')}${menu('🔔','THÔNG BÁO','XEM / XÁC NHẬN','renderNotifications()')}${menu('🕘','LỊCH SỬ','CHẤM CÔNG','renderHistory()')}</div></section>`)}
function menu(i,t,s,fn){return `<button class="menu-card" onclick="${fn}"><span class="ico">${i}</span>${t}<small>${s}</small></button>`}
function currentShift(){const now=new Date(),m=now.getHours()*60+now.getMinutes();return S.shifts.find(s=>{const a=String(s.START_TIME||'').split(':').map(Number),b=String(s.END_TIME||'').split(':').map(Number);if(a.length<2||b.length<2||a.some(Number.isNaN)||b.some(Number.isNaN))return false;let st=a[0]*60+a[1],en=b[0]*60+b[1],mm=m;if(en<=st){if(mm<st)mm+=1440;en+=1440}return mm>=st&&mm<=en})||null}
function attendanceForShift(id,date=localDate()){return S.attendance.find(a=>a.WORK_DATE===date&&String(a.SHIFT_ID)===String(id))||null}
function renderAttendance(){screen='attendance';const sh=currentShift(),att=sh?attendanceForShift(sh.SHIFT_ID):null;const open=!!(att&&att.CHECKIN_TIME&&!att.CHECKOUT_TIME);const done=!!(att&&att.CHECKOUT_TIME);page(`<section class="screen wrap"><button class="back" onclick="goBack()">← QUAY LẠI</button><h1 class="screen-title">CHẤM CÔNG</h1><div class="card"><div class="row-head"><b>CA HIỆN TẠI</b><span class="status-pill ${done?'ok':open?'warn':'ok'}">${done?'ĐÃ HOÀN TẤT':open?'ĐÃ VÀO – CHỜ RA':'SẴN SÀNG'}</span></div><div class="field"><label>Công trình</label><select id="projectSelect">${S.projects.length?S.projects.map(p=>`<option value="${esc(p.PROJECT_ID)}">${esc(p.PROJECT_NAME)}</option>`).join(''):'<option value="">Không có công trình hoạt động</option>'}</select></div><div class="field"><label>Ca làm</label><input disabled value="${sh?esc(sh.SHIFT_NAME):'Chưa có ca'}"></div>${done?`<div class="success-card"><div class="success-icon">✓</div><h2>RA CA THÀNH CÔNG</h2><p>Ca hôm nay đã hoàn tất.</p></div>`:open?`<div class="success-card compact"><h2>VÀO CA THÀNH CÔNG</h2><p>Chỉ còn thao tác RA CA.</p><button class="btn red full attendance-btn" onclick="checkout()">RA CA</button></div>`:`<button class="btn green full attendance-btn" onclick="checkin()">VÀO CA</button>`}</div></section>`);selectNearestProject()}
function selectNearestProject(){if(!navigator.geolocation||!S.projects.length)return;navigator.geolocation.getCurrentPosition(pos=>{let best=S.projects[0],bd=Infinity;S.projects.forEach(p=>{const d=geo(pos.coords.latitude,pos.coords.longitude,p.LAT,p.LNG);if(d<bd){bd=d;best=p}});if($('projectSelect'))$('projectSelect').value=best.PROJECT_ID},()=>{}, {enableHighAccuracy:true,timeout:7000,maximumAge:60000})}
function geo(a,b,c,d){const R=6371000,r=x=>x*Math.PI/180,da=r(c-a),db=r(d-b),q=Math.sin(da/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(db/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function getLocation(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(Error('Thiết bị không hỗ trợ GPS.'));navigator.geolocation.getCurrentPosition(p=>resolve(p.coords),e=>reject(Error('Không lấy được vị trí GPS.')),{enableHighAccuracy:true,timeout:10000,maximumAge:30000})})}
async function checkin(){const btn=document.querySelector('.attendance-btn');if(btn)btn.disabled=true;const projectId=$('projectSelect')?.value;if(!projectId)return toast('Chưa có công trình để chọn.');const sh=currentShift();if(!sh)return toast('Hiện không trong giờ ca.');const eventId='EVT_'+crypto.randomUUID().replaceAll('-','');const eventTime=localTime();let c={lat:'',lng:'',accuracy:0};try{const x=await getLocation();c={lat:x.latitude,lng:x.longitude,accuracy:x.accuracy}}catch(e){}if(!navigator.onLine){queueEvent({eventId,action:'CHECKIN',projectId,shiftId:sh.SHIFT_ID,workDate:localDate(),eventTime,...c});toast('Đã lưu VÀO CA offline. Sẽ đồng bộ khi có mạng.');return}try{const q=await api('checkinPreview',{eventId,projectId,shiftId:sh.SHIFT_ID,workDate:localDate(),eventTime,...c});if(q.duplicate){await bootstrap();renderAttendance();return}if(q.needsConfirm)return confirmBox(q.userWarning,'TIẾP TỤC',async()=>{await commitAttendance(q.previewToken)});await commitAttendance(q.previewToken)}catch(e){toast(e.message)}}
async function checkout(){const btn=document.querySelector('.attendance-btn');if(btn)btn.disabled=true;const sh=currentShift(),att=sh?attendanceForShift(sh.SHIFT_ID):null;if(!att||!att.CHECKIN_TIME||att.CHECKOUT_TIME)return toast('Không có ca đang mở.');const eventId='EVT_'+crypto.randomUUID().replaceAll('-',''),eventTime=localTime();let c={lat:'',lng:'',accuracy:0};try{const x=await getLocation();c={lat:x.latitude,lng:x.longitude,accuracy:x.accuracy}}catch(e){}if(!navigator.onLine){queueEvent({eventId,action:'CHECKOUT',projectId:att.PROJECT_ID,shiftId:att.SHIFT_ID,workDate:att.WORK_DATE,eventTime,...c});toast('Đã lưu RA CA offline. Sẽ đồng bộ khi có mạng.');return}try{const q=await api('checkoutPreview',{eventId,projectId:att.PROJECT_ID,shiftId:att.SHIFT_ID,workDate:att.WORK_DATE,eventTime,...c});if(q.needsConfirm)return confirmBox(q.userWarning,'TIẾP TỤC',async()=>{await commitAttendance(q.previewToken)});await commitAttendance(q.previewToken)}catch(e){toast(e.message)}}
async function commitAttendance(pt){try{const j=await api('commitPreview',{previewToken:pt,confirmed:true});await bootstrap();renderAttendance();toast(j.needsApproval?'Đã ghi nhận. Chờ Admin duyệt.':'Đã ghi nhận thành công.')}catch(e){toast(e.message)}}
function confirmBox(text,ok,yes){$('modalTitle').textContent='XÁC NHẬN';$('modalText').textContent=text||'Bạn có muốn tiếp tục?';$('modalOk').textContent=ok||'TIẾP TỤC';$('modalCancel').textContent='HỦY';$('modal').classList.remove('hidden');$('modalOk').onclick=async()=>{$('modal').classList.add('hidden');await yes()};$('modalCancel').onclick=()=>{$('modal').classList.add('hidden')}}
function queueEvent(e){const q=JSON.parse(LS.getItem('cl_offline_queue')||'[]');if(!q.some(x=>x.eventId===e.eventId)){q.push(e);LS.setItem('cl_offline_queue',JSON.stringify(q))}}
async function syncQueue(){if(!navigator.onLine||!token)return;let q=[];try{q=JSON.parse(LS.getItem('cl_offline_queue')||'[]')}catch(e){q=[]}if(!q.length)return;try{const r=await api('syncEvents',{events:q});const good=new Set(r.results.filter(x=>x.ok).map(x=>x.eventId));LS.setItem('cl_offline_queue',JSON.stringify(q.filter(x=>!good.has(x.eventId))));if(good.size){await bootstrap();if(screen==='attendance')renderAttendance();toast('Đã đồng bộ '+good.size+' lượt offline.')}}catch(e){console.warn(e)}}
window.addEventListener('online',()=>{setNet(true);syncQueue()});window.addEventListener('offline',()=>setNet(false));
function renderStats(){screen='stats';page(`<section class="screen wrap"><button class="back" onclick="goBack()">← QUAY LẠI</button><h1 class="screen-title">THỐNG KÊ CÔNG / PHÉP</h1><div class="section-actions stats-tabs"><button id="statsDayBtn" class="btn blue" onclick="loadStats('DAY')">NGÀY</button><button id="statsMonthBtn" class="btn primary" onclick="loadStats('MONTH')">THÁNG</button></div><div class="card stats-filter"><div class="two"><div class="field" id="statsDateField"><label>Chọn ngày</label><input id="statsDate" type="date" value="${localDate()}" onchange="loadStats('DAY')"></div><div class="field" id="statsMonthField"><label>Chọn tháng</label><input id="statsMonth" type="month" value="${localMonth()}" onchange="loadStats('MONTH')"></div></div></div><div id="statsArea" class="card">Đang tải…</div></section>`);loadStats('MONTH')}
function statsShiftRow(x){const sn=x.SHIFT_NAME||shiftName(x.SHIFT_ID),pn=x.PROJECT_NAME||projectName(x.PROJECT_ID);return `<div class="stats-shift-row"><b>${esc(sn)}</b><span>${esc(pn)}</span><small>${x.STATUS==='APPROVED'?'Đã duyệt':esc(x.STATUS||'')}</small></div>`}
async function loadStats(mode){
  const day=$('statsDate')?.value||localDate(),month=$('statsMonth')?.value||localMonth();
  if($('statsDateField'))$('statsDateField').style.display=mode==='DAY'?'block':'none';
  if($('statsMonthField'))$('statsMonthField').style.display=mode==='MONTH'?'block':'none';
  if($('statsDayBtn'))$('statsDayBtn').className=mode==='DAY'?'btn blue':'btn primary';
  if($('statsMonthBtn'))$('statsMonthBtn').className=mode==='MONTH'?'btn blue':'btn primary';
  const area=$('statsArea'); if(area) area.innerHTML='<div class="loading-inline">Đang tải…</div>';
  try{
    const j=await api(mode==='DAY'?'dailyStats':'monthlyStats',mode==='DAY'?{date:day}:{month:month});
    if(mode==='DAY'){
      const rows=j.attendance||[];
      area.innerHTML=`<div class="stats-summary"><span><b>${j.summary?.workDays??rows.reduce((n,x)=>n+Number(x.WORK_DAYS||0),0)}</b><small>Tổng công ngày</small></span><span><b>${j.summary?.hours??0}</b><small>Giờ làm</small></span></div><div class="stats-day"><h3>Ngày ${esc(formatVNDate(j.date))}</h3>${rows.length?rows.map(statsShiftRow).join(''):'Không có ca làm được duyệt.'}</div>`;
    }else{
      const g=j.grouped||[];
      area.innerHTML=`<div class="stats-summary"><span><b>${j.summary?.workDays??0}</b><small>Tổng công tháng ${esc(formatMonthVN(j.month))}</small></span><span><b>${j.summary?.leave??0}</b><small>Ngày phép</small></span><span><b>${j.summary?.late??0}</b><small>Đi muộn</small></span><span><b>${j.summary?.early??0}</b><small>Về sớm</small></span></div><div class="stats-month-detail"><h3>Chi tiết công tháng ${esc(formatMonthVN(j.month))}</h3>${g.length?g.map(d=>`<details class="stats-day"><summary>Ngày ${esc(formatVNDate(d.date))}</summary>${d.rows.map(statsShiftRow).join('')}</details>`).join(''):'Chưa có ngày công được duyệt.'}</div>`;
    }
  }catch(e){if(area)area.textContent=e.message}
}
function stat(v,t){return `<div class="stat"><b>${v}</b><span>${t}</span></div>`}
function formatVNDate(v){if(!v)return'';const s=String(v).slice(0,10);const m=s.match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[3]}/${m[2]}/${m[1]}`:String(v)}
function formatMonthVN(v){const m=String(v||'').match(/^(\d{4})-(\d{2})$/);return m?`${m[2]}/${m[1]}`:String(v||'')}
function shiftDisplay(id){const s=S.shifts.find(x=>String(x.SHIFT_ID)===String(id));if(!s)return shiftName(id);return `${s.SHIFT_NAME} · ${String(s.START_TIME||'').slice(0,5)} – ${String(s.END_TIME||'').slice(0,5)}`}
function assignmentNoticeHTML(n, compact=false){const date=n.WORK_DATE||n.ASSIGNMENT_DATE||'';const title=n.TASK_TITLE||n.MESSAGE||'';const note=n.NOTE||'';const shift=n.SHIFT_NAME||shiftName(n.SHIFT_ID);const st=String(n.START_TIME||'').slice(0,5),en=String(n.END_TIME||'').slice(0,5);return `<div class="assignment-notice ${compact?'compact':''}"><div class="notice-line"><span>Ngày phân công</span><b>${esc(formatVNDate(date))}</b></div><div class="notice-block"><span>Nội dung công việc</span><strong>${esc(title)}</strong>${note?`<p>${esc(note)}</p>`:''}</div><div class="notice-line"><span>Ca</span><b>${esc(shift)}${st&&en?` · ${esc(st)} – ${esc(en)}`:''}</b></div></div>`}
function renderWork(){screen='work';const rows=S.assignments||[];page(`<section class="screen wrap"><button class="back" onclick="goBack()">← QUAY LẠI</button><h1 class="screen-title">CÔNG VIỆC</h1><div class="card work-list">${rows.length?rows.map(x=>assignmentNoticeHTML(x,true)).join(''):'Chưa có công việc được phân công hôm nay.'}</div></section>`);if(navigator.onLine)api('bootstrap').then(j=>{applyBootstrap(j);saveSnapshot(j);if(screen==='work')renderWork()}).catch(()=>{})}
let leaveDates=[localDate()];function renderLeave(){screen='leave';page(`<section class="screen wrap"><button class="back" onclick="goBack()">← QUAY LẠI</button><h1 class="screen-title">BÁO PHÉP</h1><div class="card"><div class="field"><label>Ngày nghỉ</label><div class="date-add"><input id="leaveDate" type="date" value="${localDate()}"><button class="btn light" onclick="addLeaveDate()">THÊM NGÀY</button></div></div><div id="leaveDates" class="chips"></div><div class="field"><label>Ca nghỉ</label><select id="leaveShift"><option value="SANG">SÁNG</option><option value="CHIEU">CHIỀU</option><option value="TOI">TỐI</option><option value="NGAY">NGÀY</option></select></div><div class="field"><label>Lý do</label><textarea id="leaveReason"></textarea></div><button class="btn blue full" onclick="sendLeave()">GỬI ĐỀ NGHỊ</button></div></section>`);renderLeaveDates()}
function renderLeaveDates(){$('leaveDates').innerHTML=leaveDates.map(d=>`<span class="chip">${d}<button onclick="removeLeaveDate('${d}')">×</button></span>`).join('')}
function addLeaveDate(){const d=$('leaveDate').value;if(d&&!leaveDates.includes(d))leaveDates.push(d);renderLeaveDates()}function removeLeaveDate(d){leaveDates=leaveDates.filter(x=>x!==d);if(!leaveDates.length)leaveDates=[localDate()];renderLeaveDates()}
async function sendLeave(){try{const btn=document.querySelector('button[onclick="sendLeave()"]');if(btn)btn.disabled=true;await api('leaveRequest',{DATES:leaveDates,SHIFT:$('leaveShift').value,REASON:$('leaveReason').value});toast('Đã gửi đề nghị nghỉ phép.');leaveDates=[localDate()];renderUserHome();refreshUnread()}catch(e){toast(e.message)}}
async function refreshUnread(){if(!token||!navigator.onLine)return;try{const j=await api('notificationsUser');const prev=S.unread||[];S.notifications=j.rows||[];S.unread=S.notifications.filter(x=>!x.READ_AT);if(S.unread.length>prev.length&&screen!=='notifications')showUnread()}catch(e){}}
async function renderNotifications(){screen='notifications';const rows=(S.notifications&&S.notifications.length?S.notifications:S.unread||[]).concat([]);page(`<section class="screen wrap"><button class="back" onclick="goBack()">← QUAY LẠI</button><h1 class="screen-title">THÔNG BÁO</h1><div class="card notice-list">${rows.length?rows.map(n=>`<div class="work-item"><div class="notice-title">${esc(n.TITLE||'THÔNG BÁO')}</div>${n.TYPE==='ASSIGNMENT'?assignmentNoticeHTML(n):`<p class="notice-message">${esc(n.MESSAGE||'')}</p>`}<div class="notice-state">${n.READ_AT?'Đã xem':'MỚI'}</div>${!n.READ_AT?`<button class="btn blue" onclick="readNotif('${esc(n.NOTIFICATION_ID)}')">XEM</button>`:''}</div>`).join(''):'Chưa có thông báo.'}</div></section>`);if(navigator.onLine)api('notificationsUser').then(j=>{S.notifications=j.rows||[];S.unread=S.notifications.filter(x=>!x.READ_AT);if(screen==='notifications')renderNotifications()}).catch(()=>{})}
async function readNotif(id){await api('markNotificationRead',{NOTIFICATION_ID:id});S.unread=(S.unread||[]).filter(x=>String(x.NOTIFICATION_ID)!==String(id));S.notifications=(S.notifications||[]).map(x=>String(x.NOTIFICATION_ID)===String(id)?Object.assign({},x,{READ_AT:new Date().toISOString()}):x);renderNotifications()}
async function showUnread(){if(!S.unread?.length)return;const n=S.unread[0];$('modalTitle').textContent='🔔 '+(n.TITLE||'THÔNG BÁO');$('modalText').innerHTML=n.TYPE==='ASSIGNMENT'?assignmentNoticeHTML(n):`<div class="notice-hero">${esc(n.MESSAGE||'')}</div>`;$('modalCancel').textContent='ĐÓNG';$('modalOk').textContent='XEM';$('modal').classList.remove('hidden');$('modalOk').onclick=async()=>{await api('markNotificationRead',{NOTIFICATION_ID:n.NOTIFICATION_ID});$('modal').classList.add('hidden');S.unread=S.unread.slice(1);setTimeout(showUnread,80)};$('modalCancel').onclick=()=>{$('modal').classList.add('hidden')}}
async function renderHistory(){screen='history';try{const j=await api('userHistory');page(`<section class="screen wrap"><button class="back" onclick="goBack()">← QUAY LẠI</button><h1 class="screen-title">LỊCH SỬ</h1><div class="card table-wrap"><table class="table"><thead><tr><th>Ngày</th><th>Ca</th><th>Trạng thái</th></tr></thead><tbody>${j.rows.map(x=>`<tr><td>${x.WORK_DATE}</td><td>${esc(shiftName(x.SHIFT_ID))}</td><td>${esc(x.STATUS)}</td></tr>`).join('')}</tbody></table></div></section>`)}catch(e){toast(e.message)}}
function renderAdminHome(){screen='adminHome';page(`<section class="screen wrap"><div class="home-head"><div><div class="user-name">${esc(me?.NAME||'')}</div><div class="user-role">QUẢN TRỊ VIÊN</div></div><div class="icon-actions"><button class="icon-btn" onclick="adminNotifications()">🔔</button></div></div><div class="admin-menu">${menu('📈','TỔNG QUAN','Dashboard','adminDashboard()')}${menu('👥','NHÂN VIÊN','Thêm / sửa / trạng thái','adminEmployees()')}${menu('📍','CÔNG TRÌNH','GPS / bán kính','adminProjects()')}${menu('⏱','CA LÀM','Giờ ca theo mùa','adminShifts()')}${menu('✅','DUYỆT CÔNG','Chờ duyệt','adminAttendance()')}${menu('🧾','CÔNG BỔ SUNG','Sáng / Chiều / Tối / Ngày','adminMakeup()')}${menu('👨‍👩‍👧','NHÓM','Nhóm làm việc','adminGroups()')}${menu('📋','PHÂN CÔNG','Nhân viên / công trình / ca','adminAssignments()')}${menu('📝','NGHỈ PHÉP','Duyệt đơn','adminLeave()')}${menu('🔔','THÔNG BÁO','Gửi / lịch sử','adminNotifications()')}${menu('📄','BÁO CÁO','Ngày / tháng / A4','adminReports()')}${menu('🛡','NHẬT KÝ','Audit','adminLogs()')}</div></section>`)}
function adminShell(title,body){screen='admin:'+title;page(`<section class="screen wrap"><button class="back" onclick="goBack()">← QUAY LẠI</button><h1 class="screen-title">${title}</h1>${body}</section>`)}
async function adminDashboard(){try{const j=await api('adminDashboard');adminShell('TỔNG QUAN',`<div class="stats">${stat(j.activeUsers,'Nhân viên hoạt động')}${stat(j.pendingAttendance,'Công chờ duyệt')}${stat(j.pendingLeave,'Phép chờ duyệt')}${stat(j.activeProjects,'Công trình')}${stat(j.activeGroups,'Nhóm hoạt động')}</div><div class="card"><b>Phiên bản backend:</b> ${esc(j.version)}</div>`)}catch(e){toast(e.message)}}
async function adminEmployees(){try{const j=await api('adminEmployees');adminShell('NHÂN VIÊN',`<div class="section-actions"><button class="btn blue" onclick="employeeForm()">+ THÊM NHÂN VIÊN</button></div><div class="card table-wrap"><table class="table"><thead><tr><th>Mã</th><th>Họ tên</th><th>Điện thoại</th><th>Vai trò</th><th>Trạng thái</th><th></th></tr></thead><tbody>${j.rows.map(x=>`<tr><td>${esc(x.EMPLOYEE_ID)}</td><td>${esc(x.NAME)}</td><td>${esc(x.PHONE)}</td><td>${esc(x.ROLE)}</td><td>${esc(x.STATUS)}</td><td><button class="btn light" onclick='employeeForm(${JSON.stringify(x).replace(/'/g,"&#39;")})'>SỬA</button></td></tr>`).join('')}</tbody></table></div>`)}catch(e){toast(e.message)}}
function employeeForm(x={}){adminShell('THÊM / SỬA NHÂN VIÊN',`<div class="card"><div class="two"><div class="field"><label>Mã nhân viên</label><input id="ef_id" value="${esc(x.EMPLOYEE_ID||'')}"></div><div class="field"><label>Họ tên</label><input id="ef_name" value="${esc(x.NAME||'')}"></div></div><div class="two"><div class="field"><label>Số điện thoại</label><input id="ef_phone" value="${esc(x.PHONE||'')}"></div><div class="field"><label>Vai trò</label><select id="ef_role"><option value="USER" ${x.ROLE==='USER'?'selected':''}>USER</option><option value="ADMIN" ${x.ROLE==='ADMIN'?'selected':''}>ADMIN</option></select></div></div><div class="field"><label>Mật khẩu khởi tạo / reset (để trống nếu không đổi)</label><input id="ef_pw" type="password"></div><div class="field"><label>Trạng thái</label><select id="ef_status"><option value="ACTIVE" ${x.STATUS!=='INACTIVE'?'selected':''}>ACTIVE</option><option value="INACTIVE" ${x.STATUS==='INACTIVE'?'selected':''}>INACTIVE</option></select></div><input id="ef_original_id" type="hidden" value="${esc(x.EMPLOYEE_ID||"")}"><input id="ef_original_phone" type="hidden" value="${esc(x.PHONE||"")}"><button class="btn blue full" onclick="saveEmployee()">LƯU</button></div>`)}
async function saveEmployee(){try{await api('adminSaveEmployee',{ORIGINAL_EMPLOYEE_ID:$('ef_original_id').value,ORIGINAL_PHONE:$('ef_original_phone').value,EMPLOYEE_ID:$('ef_id').value,NAME:$('ef_name').value,PHONE:$('ef_phone').value,ROLE:$('ef_role').value,STATUS:$('ef_status').value,password:$('ef_pw').value});toast('Đã lưu nhân viên.');adminEmployees()}catch(e){toast(e.message)}}
async function adminProjects(){try{const j=await api('adminProjects');adminShell('CÔNG TRÌNH',`<div class="section-actions"><button class="btn blue" onclick="projectForm()">+ THÊM CÔNG TRÌNH</button></div><div class="card table-wrap"><table class="table"><thead><tr><th>Mã</th><th>Công trình</th><th>GPS</th><th>Bán kính</th><th>Trạng thái</th><th></th></tr></thead><tbody>${j.rows.map(x=>`<tr><td>${esc(x.PROJECT_ID)}</td><td>${esc(x.PROJECT_NAME)}<small>${esc(x.ADDRESS)}</small></td><td>${esc(x.LAT)}, ${esc(x.LNG)}</td><td>${esc(x.RADIUS_M)} m</td><td>${esc(x.STATUS)}</td><td><button class="btn light" onclick='projectForm(${JSON.stringify(x).replace(/'/g,"&#39;")})'>SỬA</button></td></tr>`).join('')}</tbody></table></div>`)}catch(e){toast(e.message)}}
function projectForm(x={}){adminShell('CÔNG TRÌNH',`<div class="card"><div class="two"><div class="field"><label>Mã công trình</label><input id="pf_id" value="${esc(x.PROJECT_ID||'')}"></div><div class="field"><label>Tên công trình</label><input id="pf_name" value="${esc(x.PROJECT_NAME||'')}"></div></div><div class="field"><label>Địa chỉ</label><input id="pf_address" value="${esc(x.ADDRESS||'')}"></div><div class="field"><label>Tọa độ Google Maps</label><input id="pf_coord" placeholder="16.467812, 107.590421" value="${x.LAT!==undefined?esc(x.LAT+', '+x.LNG):''}"></div><div class="two"><div class="field"><label>Bán kính (m)</label><input id="pf_radius" type="number" min="10" value="${esc(x.RADIUS_M||100)}"></div><div class="field"><label>Trạng thái</label><select id="pf_status"><option value="ACTIVE">ACTIVE</option><option value="INACTIVE">INACTIVE</option></select></div></div><button class="btn blue full" onclick="saveProject()">LƯU</button></div>`);if(x.STATUS)$('pf_status').value=x.STATUS}
async function saveProject(){try{await api('adminSaveProject',{PROJECT_ID:$('pf_id').value,PROJECT_NAME:$('pf_name').value,ADDRESS:$('pf_address').value,COORDINATES:$('pf_coord').value,RADIUS_M:$('pf_radius').value,STATUS:$('pf_status').value});toast('Đã lưu công trình.');adminProjects()}catch(e){toast(e.message)}}
async function adminShifts(){try{const j=await api('adminShifts');window._shiftRows=j.rows||[];adminShell('CA LÀM',`<div class="shift-grid">${j.rows.map(x=>`<div class="shift-card"><div class="shift-name"><b>${esc(x.SHIFT_NAME)}</b><small>${esc(x.SHIFT_ID)}</small></div><div class="shift-times"><label>VÀO<input type="time" value="${esc(x.START_TIME)}" onchange="quickShift('${esc(x.SHIFT_ID)}',this.value,'start')"></label><span>→</span><label>RA<input type="time" value="${esc(x.END_TIME)}" onchange="quickShift('${esc(x.SHIFT_ID)}',this.value,'end')"></label></div><div class="shift-tolerances"><label>TRỄ (phút)<input type="number" min="0" max="180" value="${esc(x.LATE_TOL_MIN??15)}" onchange="quickShift('${esc(x.SHIFT_ID)}',this.value,'late')"></label><label>SỚM (phút)<input type="number" min="0" max="180" value="${esc(x.EARLY_TOL_MIN??0)}" onchange="quickShift('${esc(x.SHIFT_ID)}',this.value,'early')"></label></div><span class="status-pill ${x.STATUS==='ACTIVE'?'ok':'warn'}">${esc(x.STATUS)}</span></div>`).join('')}</div><div class="section-actions no-print"><button class="btn blue" onclick="shiftForm()">+ THÊM CA</button></div>`)}catch(e){toast(e.message)}}
async function quickShift(id,value,side){try{const row=(window._shiftRows||[]).find(x=>String(x.SHIFT_ID)===String(id));if(!row)return;const n=Number(value);if((side==='late'||side==='early')&&(!Number.isFinite(n)||n<0||n>180))return toast('Ngưỡng trễ/sớm phải từ 0 đến 180 phút.');if(side==='start')row.START_TIME=value;if(side==='end')row.END_TIME=value;if(side==='late')row.LATE_TOL_MIN=n;if(side==='early')row.EARLY_TOL_MIN=n;await api('adminSaveShift',{SHIFT_ID:id,SHIFT_NAME:row.SHIFT_NAME,START_TIME:row.START_TIME,END_TIME:row.END_TIME,LATE_TOL_MIN:row.LATE_TOL_MIN,EARLY_TOL_MIN:row.EARLY_TOL_MIN,STATUS:row.STATUS});toast(side==='late'?'Đã cập nhật ngưỡng TRỄ.':side==='early'?'Đã cập nhật ngưỡng SỚM.':'Đã cập nhật giờ ca.')}catch(e){toast(e.message);adminShifts()}}

function shiftForm(x={}){adminShell('CA LÀM',`<div class="card"><div class="two"><div class="field"><label>Mã ca</label><input id="sf_id" value="${esc(x.SHIFT_ID||'')}"></div><div class="field"><label>Tên ca</label><input id="sf_name" value="${esc(x.SHIFT_NAME||'')}"></div></div><div class="two"><div class="field"><label>Bắt đầu</label><input id="sf_start" type="time" value="${esc(x.START_TIME||'08:00')}"></div><div class="field"><label>Kết thúc</label><input id="sf_end" type="time" value="${esc(x.END_TIME||'17:00')}"></div></div><div class="shift-tolerances"><div class="field"><label>Cho phép TRỄ (phút)</label><input id="sf_late" type="number" min="0" max="180" value="${esc(x.LATE_TOL_MIN??15)}"></div><div class="field"><label>Cho phép SỚM (phút)</label><input id="sf_early" type="number" min="0" max="180" value="${esc(x.EARLY_TOL_MIN??0)}"></div></div><div class="field"><label>Trạng thái</label><select id="sf_status"><option value="ACTIVE">ACTIVE</option><option value="INACTIVE">INACTIVE</option></select></div><button class="btn blue full" onclick="saveShift()">LƯU CA</button></div>`);if(x.STATUS)$('sf_status').value=x.STATUS}
async function saveShift(){try{await api('adminSaveShift',{SHIFT_ID:$('sf_id').value,SHIFT_NAME:$('sf_name').value,START_TIME:$('sf_start').value,END_TIME:$('sf_end').value,LATE_TOL_MIN:$('sf_late').value,EARLY_TOL_MIN:$('sf_early').value,STATUS:$('sf_status').value});toast('Đã lưu ca.');adminShifts()}catch(e){toast(e.message)}}
async function adminAttendance(){try{const j=await api('adminAttendance');adminShell('DUYỆT CÔNG',`<div class="card table-wrap"><table class="table"><thead><tr><th>Nhân viên</th><th>Ngày</th><th>Công trình</th><th>Ca</th><th>VÀO</th><th>RA</th><th></th></tr></thead><tbody>${j.rows.map(x=>`<tr><td>${esc(x.EMPLOYEE_NAME||x.EMPLOYEE_ID)}</td><td>${x.WORK_DATE}</td><td>${esc(projectName(x.PROJECT_ID))}</td><td>${esc(shiftName(x.SHIFT_ID))}</td><td>${esc(x.CHECKIN_TIME)}</td><td>${esc(x.CHECKOUT_TIME)}</td><td><button class="btn green" onclick="approveAttendance('${esc(x.ATTENDANCE_ID)}','APPROVED')">DUYỆT</button> <button class="btn red" onclick="approveAttendance('${esc(x.ATTENDANCE_ID)}','REJECTED')">TỪ CHỐI</button></td></tr>`).join('')}</tbody></table></div>`)}catch(e){toast(e.message)}}
async function approveAttendance(id,status){const b=[...document.querySelectorAll(`button[onclick*="approveAttendance('${id}'"]`)].find(Boolean);if(b)b.disabled=true;try{await api('approveAttendance',{ATTENDANCE_ID:id,STATUS:status});toast(status==='APPROVED'?'Đã duyệt.':'Đã từ chối.');adminAttendance().catch(()=>{})}catch(e){if(b)b.disabled=false;toast(e.message)}}
async function adminMakeup(){try{const [e,p]=await Promise.all([api('adminPeople'),api('adminProjects')]);adminShell('CÔNG BỔ SUNG',`<div class="card"><div class="field"><label>Nhân viên</label><select id="mf_emp">${e.rows.filter(x=>x.STATUS==='ACTIVE').map(x=>`<option value="${esc(x.EMPLOYEE_ID)}">${esc(x.NAME)}</option>`).join('')}</select></div><div class="field"><label>Ngày</label><input id="mf_date" type="date" value="${localDate()}"></div><div class="field"><label>Công trình</label><select id="mf_project">${p.rows.filter(x=>x.STATUS==='ACTIVE').map(x=>`<option value="${esc(x.PROJECT_ID)}">${esc(x.PROJECT_NAME)}</option>`).join('')}</select></div><div class="field"><label>Ca bù</label><select id="mf_shift"><option value="SANG">SÁNG</option><option value="CHIEU">CHIỀU</option><option value="TOI">TỐI</option><option value="NGAY">NGÀY</option></select></div><div class="field"><label>Lý do</label><textarea id="mf_reason"></textarea></div><button class="btn blue full" onclick="saveMakeup()">TẠO PHIẾU</button></div>`)}catch(e){toast(e.message)}}
async function saveMakeup(){try{await api('adminMakeup',{EMPLOYEE_ID:$('mf_emp').value,WORK_DATE:$('mf_date').value,PROJECT_ID:$('mf_project').value,SHIFT_PART:$('mf_shift').value,REASON:$('mf_reason').value});toast('Đã tạo công bổ sung.');renderAdminHome()}catch(e){toast(e.message)}}
async function adminGroups(){try{const j=await api('adminGroups');adminShell('NHÓM LÀM VIỆC',`<div class="section-actions"><button class="btn blue" onclick="groupForm()">+ THÊM NHÓM</button></div><div class="card table-wrap"><table class="table"><thead><tr><th>Mã</th><th>Tên nhóm</th><th>Trưởng nhóm</th><th>Trạng thái</th><th></th></tr></thead><tbody>${j.rows.map(x=>`<tr><td>${esc(x.GROUP_ID)}</td><td>${esc(x.GROUP_NAME)}</td><td>${esc(x.LEADER_ID)}</td><td>${esc(x.STATUS)}</td><td><button class="btn light" onclick='groupForm(${JSON.stringify(x).replace(/'/g,"&#39;")})'>SỬA</button></td></tr>`).join('')}</tbody></table></div>`)}catch(e){toast(e.message)}}
function groupForm(x={}){adminShell('NHÓM LÀM VIỆC',`<div class="card"><div class="two"><div class="field"><label>Mã nhóm</label><input id="gf_id" value="${esc(x.GROUP_ID||'')}"></div><div class="field"><label>Tên nhóm</label><input id="gf_name" value="${esc(x.GROUP_NAME||'')}"></div></div><div class="field"><label>Trưởng nhóm</label><input id="gf_leader" value="${esc(x.LEADER_ID||'')}"></div><div class="field"><label>Trạng thái</label><select id="gf_status"><option value="ACTIVE">ACTIVE</option><option value="INACTIVE">INACTIVE</option></select></div><button class="btn blue full" onclick="saveGroup()">LƯU NHÓM</button></div>`);if(x.STATUS)$('gf_status').value=x.STATUS}
async function saveGroup(){try{await api('adminSaveGroup',{GROUP_ID:$('gf_id').value,GROUP_NAME:$('gf_name').value,LEADER_ID:$('gf_leader').value,STATUS:$('gf_status').value});toast('Đã lưu nhóm.');adminGroups()}catch(e){toast(e.message)}}
async function adminAssignments(){try{const [a,e,p,g]=await Promise.all([api('adminAssignments'),api('adminPeople'),api('adminProjects'),api('adminGroups')]);adminShell('PHÂN CÔNG',`<div class="card"><div class="two"><div class="field"><label>Ngày</label><input id="af_date" type="date" value="${localDate()}"></div><div class="field"><label>Nhóm</label><select id="af_group"><option value="">Không chọn</option>${g.rows.filter(x=>x.STATUS==='ACTIVE').map(x=>`<option value="${esc(x.GROUP_ID)}">${esc(x.GROUP_NAME)}</option>`).join('')}</select></div></div><div class="field"><label>Công trình</label><select id="af_project">${p.rows.filter(x=>x.STATUS==='ACTIVE').map(x=>`<option value="${esc(x.PROJECT_ID)}">${esc(x.PROJECT_NAME)}</option>`).join('')}</select></div><div class="field"><label>Ca</label><select id="af_shift"><option value="SANG">SÁNG</option><option value="CHIEU">CHIỀU</option><option value="TOI">TỐI</option><option value="NGAY">NGÀY</option></select></div><div class="field"><label>Tên công việc</label><input id="af_task"></div><div class="field"><label>Ghi chú</label><textarea id="af_note"></textarea></div><div class="field"><label>Nhân viên được phân công</label><div class="select-list">${e.rows.filter(x=>x.STATUS==='ACTIVE').map(x=>`<label class="select-item"><input type="checkbox" name="af_emp" value="${esc(x.EMPLOYEE_ID)}"> <span>${esc(x.NAME)}</span></label>`).join('')}</div></div><button class="btn blue full" onclick="saveAssignment()">LƯU PHÂN CÔNG</button></div><div class="card table-wrap"><table class="table"><thead><tr><th>Ngày</th><th>Nhân viên</th><th>Công trình</th><th>Ca</th><th>Công việc</th><th></th></tr></thead><tbody>${a.rows.map(x=>`<tr><td>${esc(x.WORK_DATE)}</td><td>${esc((x.EMPLOYEE_NAMES||[]).join(', '))}</td><td>${esc(projectName(x.PROJECT_ID))}</td><td>${esc(shiftName(x.SHIFT_ID))}</td><td>${esc(x.TASK_TITLE)}</td><td><button class="btn red" onclick="deleteAssignment('${esc(x.ASSIGNMENT_ID)}')">XÓA</button></td></tr>`).join('')}</tbody></table></div>`)}catch(e){toast(e.message)}}
async function saveAssignment(){const ids=[...document.querySelectorAll('input[name="af_emp"]:checked')].map(x=>x.value);try{await api('adminSaveAssignment',{WORK_DATE:$('af_date').value,GROUP_ID:$('af_group').value,PROJECT_ID:$('af_project').value,SHIFT_PART:$('af_shift').value,TASK_TITLE:$('af_task').value,NOTE:$('af_note').value,EMPLOYEE_IDS:ids});toast('Đã lưu phân công.');adminAssignments()}catch(e){toast(e.message)}}
async function deleteAssignment(id){try{await api('adminDeleteAssignment',{ASSIGNMENT_ID:id});adminAssignments()}catch(e){toast(e.message)}}
async function adminLeave(){try{const j=await api('adminLeave',{STATUS:'PENDING'});adminShell('NGHỈ PHÉP',`<div class="card table-wrap"><table class="table"><thead><tr><th>Nhân viên</th><th>Ngày</th><th>Ca</th><th>Lý do</th><th></th></tr></thead><tbody>${j.rows.map(x=>`<tr><td>${esc(x.EMPLOYEE_NAME||x.EMPLOYEE_ID)}</td><td>${esc(x.WORK_DATE)}</td><td>${esc(x.SHIFT)}</td><td>${esc(x.REASON)}</td><td><button class="btn green" onclick="leaveDecision('${esc(x.LEAVE_ID)}','APPROVED')">DUYỆT</button> <button class="btn red" onclick="leaveDecision('${esc(x.LEAVE_ID)}','REJECTED')">TỪ CHỐI</button></td></tr>`).join('')}</tbody></table></div>`)}catch(e){toast(e.message)}}
async function leaveDecision(id,status){try{await api('adminLeaveDecision',{LEAVE_ID:id,STATUS:status});adminLeave()}catch(e){toast(e.message)}}
async function adminNotifications(){try{const [j,e]=await Promise.all([api('adminNotifications'),api('adminPeople')]);adminShell('THÔNG BÁO',`<div class="card"><div class="field"><label>Nhân viên</label><select id="nf_emp">${e.rows.filter(x=>x.STATUS==='ACTIVE').map(x=>`<option value="${esc(x.EMPLOYEE_ID)}">${esc(x.NAME)}</option>`).join('')}</select></div><div class="field"><label>Tiêu đề</label><input id="nf_title"></div><div class="field"><label>Nội dung</label><textarea id="nf_msg"></textarea></div><button class="btn blue full" onclick="sendAdminNotif()">GỬI THÔNG BÁO</button></div><div class="card table-wrap"><table class="table"><thead><tr><th>Nhân viên</th><th>Tiêu đề</th><th>Đã xem</th></tr></thead><tbody>${j.rows.map(x=>`<tr><td>${esc(x.EMPLOYEE_NAME||x.EMPLOYEE_ID)}</td><td>${esc(x.TITLE)}</td><td>${x.READ_AT?'Có':'Chưa'}</td></tr>`).join('')}</tbody></table></div>`)}catch(e){toast(e.message)}}
async function sendAdminNotif(){try{await api('adminNotifications',{send:true,EMPLOYEE_ID:$('nf_emp').value,TITLE:$('nf_title').value,MESSAGE:$('nf_msg').value});toast('Đã gửi.');adminNotifications()}catch(e){toast(e.message)}}
async function adminReports(){try{const e=await api('adminEmployees');adminShell('BÁO CÁO',`<div class="card"><div class="two"><div class="field"><label>Loại</label><select id="rp_mode" onchange="syncReportDateField()"><option value="MONTH">THÁNG</option><option value="DAY">NGÀY</option></select></div><div class="field"><label>Nhân viên</label><select id="rp_emp"><option value="ALL">Tất cả</option>${e.rows.map(x=>`<option value="${esc(x.EMPLOYEE_ID)}">${esc(x.NAME)} — ${esc(x.EMPLOYEE_ID)}</option>`).join('')}</select></div></div><div class="field"><label id="rp_date_label">Tháng</label><input id="rp_date" type="month" value="${localMonth()}"></div><div class="section-actions"><button class="btn blue" onclick="loadReport()">XEM BÁO CÁO</button></div><div id="reportArea">Chọn điều kiện rồi xem báo cáo.</div></div>`);syncReportDateField()}catch(e){toast(e.message)}}
function syncReportDateField(){const mode=$('rp_mode')?.value||'MONTH',i=$('rp_date'),l=$('rp_date_label');if(!i)return;if(mode==='DAY'){i.type='date';i.value=localDate();if(l)l.textContent='Ngày'}else{i.type='month';i.value=localMonth();if(l)l.textContent='Tháng'}}
async function loadReport(){try{const mode=$('rp_mode').value,date=$('rp_date').value,p={mode,employeeId:$('rp_emp').value};if(mode==='DAY')p.date=date;else p.month=date.slice(0,7);const j=await api('adminReports',p),title=mode==='DAY'?'BÁO CÁO CHẤM CÔNG THEO NGÀY':'BÁO CÁO CÔNG THÁNG',filter=$('rp_emp').value==='ALL'?'Tất cả nhân viên':$('rp_emp').selectedOptions[0]?.textContent||'',h=j.header||{},headers=[h.HEADER_1||'Cuatung Lighting',h.HEADER_2||title,h.HEADER_3||(mode==='DAY'?'Ngày '+j.date:'Tháng '+j.month),h.HEADER_4||filter];$('reportArea').innerHTML=`<div class="report-print"><div class="report-heading compact"><div class="report-row r1">${esc(headers[0])}</div><div class="report-row r2">${esc(headers[1])}</div><div class="report-row r3">${esc(headers[2])}</div><div class="report-row r4">${esc(headers[3])}</div></div><div class="report-summary">${mode==='MONTH'?`<span><b>${j.summary?.workDays??0}</b> ngày công</span><span><b>${j.summary?.hours??0}</b> giờ</span>`:`<span><b>${j.rows.length}</b> lượt công</span>`}</div><div class="table-wrap"><table class="table report-table"><thead><tr>${mode==='DAY'?'<th>Mã</th><th>Họ tên</th><th>Công trình</th><th>Ca</th><th>Vào</th><th>Ra</th><th>Giờ</th><th>TT</th>':'<th>Mã</th><th>Họ tên</th><th>Ngày công</th><th>Giờ</th><th>Phép</th><th>Muộn</th><th>Sớm</th>'}</tr></thead><tbody>${j.rows.map(x=>mode==='DAY'?`<tr><td>${esc(x.EMPLOYEE_ID)}</td><td>${esc(x.NAME)}</td><td>${esc(projectName(x.PROJECT_ID))}</td><td>${esc(shiftName(x.SHIFT_ID))}</td><td>${esc(x.CHECKIN_TIME)}</td><td>${esc(x.CHECKOUT_TIME)}</td><td>${x.WORK_HOURS}</td><td>${esc(x.STATUS)}</td></tr>`:`<tr><td>${esc(x.EMPLOYEE_ID)}</td><td><button class="report-employee-link" onclick="loadAdminEmployeeMonthDetail('${esc(x.EMPLOYEE_ID)}','${esc(j.month)}')">${esc(x.NAME)}</button></td><td>${x.WORK_DAYS}</td><td>${x.HOURS}</td><td>${x.LEAVE}</td><td>${x.LATE}</td><td>${x.EARLY}</td></tr>`).join('')}</tbody></table></div></div><div class="section-actions no-print"><button class="btn green" onclick="window.print()">XUẤT / IN A4</button><button class="btn blue" onclick="downloadCSV()">XUẤT EXCEL</button></div>`;window._reportRows=j.rows;window._reportMode=mode}catch(e){toast(e.message)}}

async function loadAdminEmployeeMonthDetail(employeeId,month){
  try{
    const j=await api('adminEmployeeMonthDetail',{employeeId,month});
    const rows=j.grouped||[];
    const total=j.summary||{};
    const back=`<button class="btn light" onclick="loadReport()">← QUAY LẠI BÁO CÁO THÁNG</button>`;
    const days=rows.length?rows.map(d=>`<details class="report-detail-day" open>
      <summary><span>Ngày ${esc(formatVNDate(d.date))}</span><b>${esc(String(d.workDays||0))} công</b></summary>
      <div class="report-detail-list">${d.rows.map(x=>`<div class="report-detail-row">
        <div class="report-detail-main"><b>${esc(x.SHIFT_NAME||x.SHIFT_PART||'Ca')}</b><span>${esc(x.PROJECT_NAME||x.PROJECT_ID||'')}</span></div>
        <div class="report-detail-meta"><span>${esc(String(x.WORK_DAYS||0))} công</span><span>${esc(String(x.WORK_HOURS||0))} giờ</span>${x.STATUS?`<span>${esc(x.STATUS==='APPROVED'?'Đã duyệt':x.STATUS)}</span>`:''}</div>
      </div>`).join('')}</div>
    </details>`).join(''):'<div class="empty">Chưa có ngày công được duyệt trong tháng này.</div>';
    const leaves=(j.leaves||[]).length?`<div class="report-leave-box"><h3>Ngày phép</h3>${j.leaves.map(x=>`<div class="report-leave-row"><b>${esc(formatVNDate(x.WORK_DATE))}</b><span>${esc(x.SHIFT||x.TYPE||'')}</span><span>${esc(x.REASON||'')}</span></div>`).join('')}</div>`:'';
    const area=$('reportArea');
    if(!area)return;
    area.innerHTML=`<div class="report-detail-head">${back}<h2>${esc(j.name||employeeId)}</h2><p>Chi tiết ngày công tháng ${esc(formatMonthVN(j.month))}</p></div>
      <div class="report-summary"><span><b>${esc(String(total.workDays||0))}</b> ngày công</span><span><b>${esc(String(total.hours||0))}</b> giờ</span><span><b>${esc(String(total.leave||0))}</b> ngày phép</span><span><b>${esc(String(total.late||0))}</b> đi muộn</span><span><b>${esc(String(total.early||0))}</b> về sớm</span></div>
      <div class="report-detail-month">${days}</div>${leaves}`;
  }catch(e){toast(e.message)}
}

function downloadCSV(){const rows=window._reportRows||[],mode=window._reportMode,head=mode==='DAY'?['Mã nhân viên','Họ và tên','Công trình','Ca làm','Giờ vào','Giờ ra','Số giờ làm','Trạng thái']:['Mã nhân viên','Họ và tên','Ngày công','Tổng số giờ','Ngày phép','Đi muộn','Về sớm'];const data=rows.map(x=>mode==='DAY'?[x.EMPLOYEE_ID,x.NAME,projectName(x.PROJECT_ID),shiftName(x.SHIFT_ID),x.CHECKIN_TIME,x.CHECKOUT_TIME,x.WORK_HOURS,x.STATUS]:[x.EMPLOYEE_ID,x.NAME,x.WORK_DAYS,x.HOURS,x.LEAVE,x.LATE,x.EARLY]);const tr=r=>'<tr>'+r.map(v=>'<td>'+esc(v??'')+'</td>').join('')+'</tr>';const html='<!doctype html><html><head><meta charset="utf-8"><style>@page{size:A4 landscape;margin:10mm}table{border-collapse:collapse;width:100%;font-family:Arial;font-size:10pt}th,td{border:1px solid #777;padding:5px}th{font-weight:700;background:#e8eef5}</style></head><body><h3>Cuatung Lighting</h3><h2>'+esc(window._reportMode==='DAY'?'BÁO CÁO CHẤM CÔNG THEO NGÀY':'BÁO CÁO CÔNG THÁNG')+'</h2><table><thead>'+tr(head.map(v=>v))+'</thead><tbody>'+data.map(tr).join('')+'</tbody></table></body></html>';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([html],{type:'application/vnd.ms-excel;charset=utf-8'}));a.download=mode==='DAY'?'bao-cao-cham-cong-ngay.xls':'bao-cao-cong-thang.xls';a.click()}
async function adminLogs(){try{const j=await api('adminLogs');adminShell('NHẬT KÝ',`<div class="card table-wrap"><table class="table"><thead><tr><th>Thời gian</th><th>Action</th><th>User</th><th>Chi tiết</th></tr></thead><tbody>${j.rows.slice().reverse().map(x=>`<tr><td>${esc(x.TIME)}</td><td>${esc(x.ACTION)}</td><td>${esc(x.USER_ID)}</td><td>${esc(x.DETAIL)}</td></tr>`).join('')}</tbody></table></div>`)}catch(e){toast(e.message)}}
function projectName(id){return S.projects.find(x=>String(x.PROJECT_ID)===String(id))?.PROJECT_NAME||id}function shiftName(id){return S.shifts.find(x=>String(x.SHIFT_ID)===String(id))?.SHIFT_NAME||id}
function showChangePassword(force){adminShell('ĐỔI MẬT KHẨU',`<div class="card"><p>${force?'Tài khoản phải đổi mật khẩu trước khi tiếp tục.':''}</p><div class="field"><label>Mật khẩu mới</label><input id="cp1" type="password"></div><div class="field"><label>Nhập lại</label><input id="cp2" type="password"></div><button class="btn blue full" onclick="changePassword()">ĐỔI MẬT KHẨU</button></div>`)}
async function changePassword(){if($('cp1').value!==$('cp2').value)return toast('Hai mật khẩu không khớp.');try{await api('changePassword',{newPassword:$('cp1').value});await bootstrap();showHome()}catch(e){toast(e.message)}}
function requestLogout(){$('modalTitle').textContent='ĐĂNG XUẤT';$('modalText').textContent='Bạn có chắc muốn đăng xuất khỏi tài khoản này?';$('modalCancel').textContent='HỦY';$('modalOk').textContent='ĐĂNG XUẤT';$('modal').classList.remove('hidden');$('modalOk').onclick=async()=>{ $('modal').classList.add('hidden'); await doLogout() };$('modalCancel').onclick=()=>{$('modal').classList.add('hidden')}} 
async function doLogout(){try{if(token)await api('logout')}catch(e){}clearSession();renderLogin()}
async function restore(){
  renderLogin();if(!token||!me)return;const snap=readSnapshot();
  if(snap&&Date.now()-snap.at<10*60*1000)applyBootstrap(snap.data);
  showHome();showUnread();
  bootstrap().then(()=>{saveSnapshot(S);if(screen==='userHome'||screen==='adminHome')showHome();showUnread()}).catch(e=>{if(/phiên đăng nhập|không hợp lệ|hết hạn/i.test(e.message)){clearSession();renderLogin()}else{setNet(false);toast('Đang sử dụng dữ liệu đã lưu. Khi có mạng sẽ cập nhật.')}})
}
function start(){const n=$('netState');if(n){n.textContent='SẴN SÀNG';n.classList.remove('offline');n.classList.add('ready')}restore();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js',{updateViaCache:'none'}).then(r=>r.update()).catch(()=>{});setTimeout(syncQueue,800);setTimeout(refreshUnread,1500);setInterval(()=>{if(token&&navigator.onLine)refreshUnread()},30000);window.addEventListener('online',()=>{setNet(true);syncQueue()});window.addEventListener('offline',()=>{if(token)setNet(false)})}
window.renderUserHome=renderUserHome;window.renderAttendance=renderAttendance;window.renderStats=renderStats;window.loadStats=loadStats;window.renderWork=renderWork;window.renderLeave=renderLeave;window.renderNotifications=renderNotifications;window.renderHistory=renderHistory;window.doLogout=doLogout;window.requestLogout=requestLogout;window.checkin=checkin;window.checkout=checkout;window.addLeaveDate=addLeaveDate;window.removeLeaveDate=removeLeaveDate;window.sendLeave=sendLeave;window.readNotif=readNotif;window.adminDashboard=adminDashboard;window.adminEmployees=adminEmployees;window.employeeForm=employeeForm;window.saveEmployee=saveEmployee;window.adminProjects=adminProjects;window.projectForm=projectForm;window.saveProject=saveProject;window.adminShifts=adminShifts;window.quickShift=quickShift;window.shiftForm=shiftForm;window.saveShift=saveShift;window.adminAttendance=adminAttendance;window.approveAttendance=approveAttendance;window.adminMakeup=adminMakeup;window.saveMakeup=saveMakeup;window.adminGroups=adminGroups;window.groupForm=groupForm;window.saveGroup=saveGroup;window.adminAssignments=adminAssignments;window.saveAssignment=saveAssignment;window.deleteAssignment=deleteAssignment;window.adminLeave=adminLeave;window.leaveDecision=leaveDecision;window.adminNotifications=adminNotifications;window.sendAdminNotif=sendAdminNotif;window.adminReports=adminReports;window.loadReport=loadReport;window.syncReportDateField=syncReportDateField;window.syncReportDateField=syncReportDateField;window.downloadCSV=downloadCSV;window.adminLogs=adminLogs;window.changePassword=changePassword;window.goBack=goBack;
start();
})();
